- Gemfile
- Gemfile.lock
- spec/factories/listings.rb
- spec/requests/listings_spec.rb
I added Faker and fixed the tests that `bin/rspec` said were failing. I'm okay with editing this change to not use faker, if anyone prefers that.
Here are some decisions this commit goes along with that we might change soon based on new requirements:
- we're not accepting zip+4 format yet
- we're not accepting Canadian postal codes yet
- listings currently must have both an email and a phone number
> fix failing tests with the addition of Faker

- .circleci/config.yml
- .env.test
- .gitignore
- Gemfile
- Gemfile.lock
- config/database.yml
- config/environments/test.rb
- spec/factories/listings.rb
- spec/requests/listings_spec.rb
Here's a Circle CI config with relevant config changes. Important notes:
- I added the `dotenv` gem because that will help with keeping testing, development, and deployment variables consistent. It may also be helpful when it comes to welcoming new people with unusual computer configurations who want to contribute
- This includes the changes in https://github.com/maebeale/mutual-aid/pull/31 because otherwise the tests would fail and because rebasing without those test fixes and then rebasing again after that's merged in would be annoying and a little silly. That said, I put the tests in a separate PR to make it easy for everyone to look at them separately. If you want to review code changes, you should probably review https://github.com/maebeale/mutual-aid/pull/31 first
Otherwise, it's …
> Add Circle CI

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/listings.scss
- app/javascript/components/PublicListings.vue
- app/javascript/components/index.js
- app/javascript/entry_points/index.js
- app/javascript/entry_points/publicListings.js
- app/views/listings/_listing.json.jbuilder
- app/views/listings/index.html.erb
- app/views/listings/index.json.jbuilder
- spec/requests/listings_spec.rb
This is an initial go at putting the listings page in Vue. I forget who recommend it this past weekend, but the gist is that the listing page makes more sense as a first place to get Vue up and working than the listing form for creating & editing listings. This is my skeleton for that page. Some things are missing, as might be obvious in the screenshot below. I'll also make a note of them in comments further down
> move listings page into vue

- app/views/layouts/application.html.erb
- app/views/layouts/public.html.erb
Seems obvious now, but blew a couple hours trying to figure out why things that should have been responsive weren't behaving that way!
[Reference](https://developer.mozilla.org/en-US/docs/Mozilla/Mobile/Viewport_meta_tag)
> Set viewport meta-tag since our site is responsive

- .circleci/config.yml
- bin/test
- config/webpack/test.js
- package-lock.json
- package.json
- test/setup.js
- yarn.lock
This adds JS testing. 
This expects all JS test files to live under the folder `test` and end with `.spec.js`. This is a convention I've seen in other projects. Honestly, I don't like this structure. I feel like having a `spec` folder and a `test` folder is weird and confusing. I'm not sure what to use instead, however.
This will allow you to run JS tests by:
* running `npm test` or `yarn test`, which will run the JS tests only
* running `bin/test` which will run the JS tests after running the rspec tests and only if the rspec tests succeed
* triggering a CircleCI run. The CircleCI uses `yarn test` instead of `npm test` because yarn handles passing through and appending additional arguments nicely
There is probably a way to write `config/webpack/test.js` so that the test run more …
> Add js testing with mochapack

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/bulma_and_buefy.scss
- app/assets/stylesheets/bulma_customization.scss
- app/assets/stylesheets/simple_form_customization.scss
- package.json
- yarn.lock
Two tweaks became apparent as i started to use Buefy:
1. Its probably best for us to use the Bulma version that is specified in the Buefy dependencies so that we are using the version they test against. I haven't run into any incompatibilities yet, but figured this would be safer until there's a reason to pull in the latest Bulma.
2. The css overrides for SimpleForm+Bulma were defined globally and broke Buefy. Since they should only be needed within a SimpleForm, i've scoped them accordingly. Note: i didn't test this because i'm not familiar with the specific tweaks. LMK if this works, @maebeale .
> Pin Bulma version to Buefy, scope overrides for SimpleForm

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/font_awesome.scss
- app/javascript/components/DeleteButton.vue
- app/javascript/components/NavBar.vue
- app/javascript/components/Notice.vue
- app/javascript/entry_points/index.js
- app/javascript/entry_points/navBar.js
- app/javascript/entry_points/notice.js
- app/javascript/our_vue.js
- app/views/layouts/_navbar.html.erb
- app/views/layouts/_notices_and_alerts.html.erb
- app/views/layouts/application.html.erb
- config/webpack/environment.js
- package.json
- yarn.lock
1. Get font-awesome working.
1. Cleanup `layouts/application.html.erb`.
1. Sort out `.container` and `.section` use in our site-wide layout (see notes below).
1. Switch `nav` to use `buefy`.
1. Extract reusable `DeleteButton` component.
1. Switch notices to use `buefy`.
See individual commit comments for more details.
May also be easier to review the changes one commit at a time.
Played around with two different buefy components for displaying notices:
I prefer the Snackbar, mostly because its less intrusive -- the Message banner takes up a lot of screen-space. Most of the time we'll be showing informational messages, so it feels a bit too heavy.
> Several improvements to layout code

- app/assets/stylesheets/listings.scss
- app/javascript/components/TagList.vue
- app/javascript/pages/browse/ContactIcons.vue
- app/javascript/pages/browse/TileBrowser.vue
- app/javascript/pages/browse/TileListItem.vue
- lib/listings.json
- package.json
- spec/javascript/components/TagList.spec.js
- spec/javascript/pages/browse/ContactIcons.spec.js
- spec/javascript/pages/browse/ListBrowser.spec.js
- spec/javascript/pages/browse/TileBrowser.spec.js
- yarn.lock
I've got this so it looks fine on mobile, and on larger screens. There's some weirdness at intermediate sizes, which I'll post screenshots at below. I'm still learning a lot about CSS, haven't really done much with flexbox before now, so suggestions are welcome.
Also, I'm not really happy with how the content of these `<style>` tags in the components look. The feel rambling and hard to scan to me. I'd definitely appreciate organizational suggestions for them
Not sure how best to deal with this (see pointy arrow) behavior where the tags are too big to fit. I figure it's a UI problem because for some people it will break their ability to scan through the cards easily.
I like wrapping better than the ol' css overflow.
I think it's more important to move on to filtering functionality first. I …
> Add more data to tiles

- app/controllers/application_controller.rb
- app/controllers/communication_logs_controller.rb
- app/controllers/concerns/deliver_now_with_error_handling.rb
- app/controllers/submissions_controller.rb
- app/helpers/application_helper.rb
- app/mailers/submission_mailer.rb
- app/models/communication_log.rb
- app/models/organization.rb
- app/models/person.rb
- app/models/position.rb
- app/models/system_setting.rb
- app/views/communication_logs/_form.html.erb
- app/views/communication_logs/show.html.erb
- app/views/layouts/_view_header.html.erb
- app/views/submission_mailer/_generic_confirmation_email.html.erb
- app/views/submission_mailer/_generic_show_for_email.html.erb
- app/views/submission_mailer/new_submission_confirmation_email.html.erb
- app/views/submission_mailer/new_submission_confirmation_email.text.erb
- app/views/submissions/_form.html.erb
- app/views/submissions/index.html.erb
- app/views/submissions/show.html.erb
- db/seeds.rb
This PR creates plumbing for sending confirmation emails after form "Submissions" are created, and then logging the autoemail in a `CommunicationLog`. It includes `SubmissionMailer` mailer file and view templates.
This process of sending autoemails requires some built-in knowledge within the system of who within the `Organization` should get notified of new `submissions` and be suggested to an unauthenticated user  as a point of contact for questions.
It starts to tease out some more detail wrt `SystemSettings`, system `exchange_types`, and the overall workflow, which will later inform a state machine on `Listing`.
* Add mailer and views for confirmation emails
* Change `SubmissionsController` create action so emails are sent after `@submission.save`
* Add `DeliverNowWithErrorHandling` …
> Send autoemails and log after submission create

- app/controllers/people_controller.rb
- app/views/people/_form.html.erb
- db/migrate/20200503224311_add_preferred_locale_to_person.rb
- db/schema.rb
Add `preferred_locale` to Person
Not adding this to User, bc we want to know everyone's preferred locale for ease of communications between volunteers/coordinators/providers/receivers.
We reference this value when sending Submission confirmation emails, but aren't yet rigged up for sending confirmation emails in different languages.
> Add locale to person

- app/javascript/entry_points/browse.js
- app/javascript/entry_points/navBar.js
- app/javascript/entry_points/orientation.js
- app/javascript/entry_points/publicListings.js
- app/javascript/our_vue.js
- app/javascript/vue_config.js
- lib/listings.json
- spec/javascript/components/TagList.spec.js
- spec/javascript/pages/browse/ContactIcons.spec.js
- spec/javascript/pages/browse/ListBrowser.spec.js
- spec/javascript/pages/browse/TileBrowser.spec.js
1. 0e8085f : Eliminate Vue warning about duplicate keys when running specs
1. a039955 : Ensure all specs have a top-level describe block to help with output grouping
1. 4352e79: Rework vue configuration so it can be safely reused in specs without polluting a shared global Vue instance between specs.
Note: the diffs from number #2 above are mostly just whitespace, so i recommend ignoring whitespace changes on review.
> Some improvements to our JS specs

- Gemfile
- Gemfile.lock
- Guardfile
- app/interactors/base_interactor.rb
- app/interactors/save_listing.rb
- app/interactors/save_location.rb
- app/interactors/save_person.rb
- spec/interactors/save_listing_spec.rb
- spec/interactors/save_person_spec.rb
Demonstrates using [ActiveInteraction](https://github.com/AaronLasseigne/active_interaction#rails) gem to help manage nested models involved in creating a listing: `Listing -> Person -> Location`.
It may be easier to review each of the two substantive commits separately, because the last one introduces a further abstraction on top of the gem.
While `compose` helps with calling one interactor from another, it doesn't handle two things that are important when dealing with nested forms:
1. merging errors from the child object into the parent
2. rolling back child records if parent records later fail
I've introduced the `merging_errors` method to remove the duplication involved with handling those considerations.
Note: i haven't defined all the necessary fields for any of these models. Just …
> First draft of using interactors for nested forms

- app/views/layouts/_view_footer_buttons.html.erb
- Generate a delete_button if not passed in to `view_footer_buttons` partial (this is called by all forms)
- Allows you to call the partial and pass in `delete_button: ""` to NOT show a delete button (we need this for system_settings)
> Add delete button to view_footer_buttons shared partial

- .circleci/config.yml
This helps with troubleshooting Circle CI problems when the Gemfile and Gemfile.lock don't mach. Before this change, you would only see a failed step once the `ruby_tests` job started to run and the error for that failed step would me misleading as to the cause of the problem.
With this change, the error will show up in the `bundle_install` step, and will be more explicit about what the discrepancy is.
Here is a screenshot of what that more helpful error will look like:
> Improve circleci bundle install error messages

- app/controllers/people_controller.rb
- app/interactors/save_person.rb
- app/javascript/components/AuthTokenInput.vue
- app/javascript/components/DeleteButton.vue
- app/javascript/components/NavBar.vue
- app/models/contact_method.rb
- app/models/person.rb
- app/views/people/_form.html.erb
- db/migrate/20200509052637_create_contact_methods.rb
- db/migrate/20200509054235_change_person_preferred_contact_method_to_reference.rb
- db/schema.rb
- db/seeds.rb
- spec/factories/contact_methods.rb
- spec/factories/people.rb
- spec/interactors/save_listing_spec.rb
- spec/interactors/save_person_spec.rb
- spec/models/person_spec.rb
Refactors 'contact methods' into its own table-backed model.
Motivations:
1. I was finding that i needed additional data for each contact method, such as the name of the corresponding field, and label (though i ended up getting that from `i18n` instead).
1. I could see an settings page where a system admin enables/disables the available contact methods and adds their own ones.
> ContactMethod model

- app/views/software_feedbacks/edit.html.erb
- app/views/software_feedbacks/index.html.erb
- spec/factories/software_feedbacks.rb
- spec/views/software_feedbacks/edit.html.erb_spec.rb
- spec/views/software_feedbacks/index.html.erb_spec.rb
- spec/views/software_feedbacks/new.html.erb_spec.rb
- spec/views/software_feedbacks/show.html.erb_spec.rb
- spec/views/submissions/edit.html.erb_spec.rb
- spec/views/submissions/index.html.erb_spec.rb
- spec/views/submissions/new.html.erb_spec.rb
- spec/views/submissions/show.html.erb_spec.rb
- Now that the view_header and edit_button/show_button helpers handle test controller params,
these can be added back in: spec/views/software_feedbacks && spec/views/submissions
- updated software_feedbacks factory to use Time.now vs frozen string for unique data
- fixed typo on software_feedbacks/edit
- changed indentation on sofware_feedbacks/index
> Add back in some view specs & some cleanup

- app/javascript/components/NavBar.vue
Reverts maebeale/mutual-aid#132
- Logo/home button is in nav again, so this is no longer needed
> Revert "added Home link to the Vue navbar"

- app/controllers/application_controller.rb
- app/controllers/asks_controller.rb
- app/controllers/listings_controller.rb
- app/controllers/offers_controller.rb
- app/models/category.rb
- app/models/listing.rb
- app/views/listings/_form.html.erb
- app/views/listings/match.html.erb
- app/views/listings/show.html.erb
- config/routes.rb
- db/seeds.rb
- spec/models/listing_spec.rb
- spec/requests/listings_spec.rb
- Change @system_setting to create a new one if one didn't already exist (which it always should...  does that mean we should throw an exception instead?)
- Add AsksController for routing between admin, and in prep to stand up mirror of Offers.new code
- ListingsController:
- DRY up ListingsController and remove references to ListingForm (since we now have interactors)
- Correct some of the match and match_confirm actions
- Change @listing to use listing_params in ListingsController
- Add set_form_dropdowns
- Add index action to OffersController (for routing from Admin home)
- Move seed data out of category model and in to seeds.rb
- Add some scopes and methods on Listing to help w Profile display
- Replace ListingForm w a railsy Listing form partial so people can edit Listings from the …
> Listings navigation crud

- app/views/users/index.html.erb
We display permission level on User index, but this isn't implemented yet, so added explicit text to indicate that.
> Add note re permission levels not implemented yet

- .env.ci.example
- config/environments/production.rb
Change SENDGRID-specific ENV vars to SMTP bc some groups will not use SENDGRID
> Rename smtp vars accordingly rather than sendgrid-specific

- app/controllers/contributions_controller.rb
- app/controllers/listings_controller.rb
- app/controllers/matches_controller.rb
- app/models/contribution.rb
- app/views/contributions/index.html.erb
- app/views/contributions/respond.html.erb
- app/views/listings/listings_index.html.erb
- app/views/matches/_form.html.erb
- app/views/submissions/index.html.erb
- config/routes.rb
- spec/factories/contributions.rb
- spec/requests/contributions_spec.rb
- Add Respond endpoint (not sure about it living in ContributionsController, but...)
- Add links from Respond to CreateCommunicationLog, Find Match, Create Match
- Add same links to Submissions index
- Add same links to temporary `listings_index` index view (until we move contributions out of ListingsController)
- This provides @h-m-m with a Respond endpoint for the Card "Respond" (not "Contact") button can go. (View Profile is just User show)
- This can def use some refactoring next week
> Stub out responding and matching

- app/controllers/contributions_controller.rb
- app/models/contribution.rb
- app/views/contributions/index.html.erb
- config/routes.rb
- spec/factories/contributions.rb
- spec/requests/contributions_spec.rb
I started to stub out moving the `contributions` data to a ContributionsController vs doing it through the ListingsController (and redirected through PublicPagesController#contributions).
@h-m-m if any of this is helpful this week or next (or the one after that! :)), please feel free to use! :)
> Add ContributionsController, etc, (so we can move out of ListingsController)

- app/javascript/pages/browse/ListBrowser.vue
All the filtering from #236 works just fine here
Still would be nice if the site could remember whether you last used tile or list browse instead of forgetting every page load
> update list contribution browser to be in line with latest changes

- app/controllers/communication_logs_controller.rb
- app/models/communication_log.rb
- app/models/contact_method.rb
- app/views/communication_logs/_form.html.erb
- app/views/communication_logs/index.html.erb
- app/views/communication_logs/show.html.erb
- db/migrate/20200516190206_change_communication_log_fields.rb
- db/schema.rb
- Remove the from_type and to_type fields, that were dying on the vine
- Add outgoing boolean to distinguish whether the log is an incoming communication or outgoing
- Inherit from ContactMethod for delivery_method assn, since this was essentially duplicative w that data
- Add `autoemail` scope on ContacMethod to find methods that are/aren't system logs (autoemails)
> Change communication log fields

- app/mailers/submission_mailer.rb
Accept system_setting as an optional param in submission_mailer to conditionally send relevant email text.
> Add system setting to mailer

- app/blueprints/contribution_blueprint.rb
- app/javascript/pages/browse/TileListItem.vue
- spec/blueprints/contribution_blueprint_spec.rb
Resolves #331
My local timezone is set to EDT, so the time conversion here is accurate. The time conversion occurs locally, in the browser
> Update datetime on contribution json to display better in the browser

- README.md
- lib/tasks/db.rake
- Update custom db rake task names, and corresponding references in README
(I'd found myself forgetting which task was which, so hopefully these make it clearer!)
They could still be improved upon, but here's excerpt from README
```
- All options: 
- `rake db:rebuild_and_seed` (drop, create, migrate, seed, stats_check)
- `rake db:rebuild_and_seed_dev` (drop, create, migrate, seed, import_all_seeds, stats_check)
- `rake db:stats_check` (outputs record totals)
- `rake db:delete_all_data` (runs truncate on all tables)
- `rake db:truncate_tables` (runs truncate on all tables)
- `rake db:recreate_all_seeds` (delete_all_data, seed, import_all_seeds, stats_check)   
- `rake db:import_all_seeds` (import_dev_seeds, import_submission_response_seeds, import_user_seeds, …
```
> Update rake tasks

- app/views/people/_form.html.erb
Person form wasn't defaulting to previously selected `preferred_contact_timeframe`
> Display selected timeframe on Person form

- app/blueprints/category_blueprint.rb
- app/blueprints/configuration_blueprint.rb
- app/blueprints/listing_blueprint.rb
- app/blueprints/location_blueprint.rb
- app/blueprints/person_blueprint.rb
- app/blueprints/submission_blueprint.rb
- app/controllers/asks_controller.rb
- app/controllers/offers_controller.rb
- app/forms/listing_form.rb
- app/forms/location_form.rb
- app/forms/person_form.rb
- app/forms/submission_form.rb
- app/javascript/components/forms/LocationFields.vue
- app/javascript/components/forms/ServiceAreaField.vue
- app/javascript/pages/Ask.vue
- app/javascript/pages/Offer.vue
- app/javascript/utils/string.js
- app/models/application_record.rb
- app/models/location_type.rb
- app/models/service_area.rb
- spec/forms/submission_form_spec.rb
- spec/javascript/pages/Offer.spec.js
Also introduces a `ConfigurationBlueprint` object that consolidates `ServiceArea`, `LocationType`, `ContactMethod` configurations so controllers don't have to know this logic.
Fixes #191
> Add location type to ask/offer form

- app/controllers/contributions_controller.rb
- app/controllers/listings_controller.rb
- app/models/browse_filter.rb
- config/routes.rb
- spec/models/browse_filter_spec.rb
- spec/requests/contributions_spec.rb
- spec/requests/listings_spec.rb
- simplify how the browse filter parser is called from the controller
- duplicate the code from the listings controller into the contributions controller
- comment out the public_contributions route as it was masking a path mentioned later in the routes file
- get all the tests to pass
I wasn't happy with this code when I wrote it — it's too complicated for me to follow and remember what I did, and I knew that when I finished writing it. I'm glad there's a reason now for me to have a go at cleaning it up, if only partially.
> Refactor browse filtering

- app/controllers/system_settings_controller.rb
- app/views/contributions/thank_you.html.erb
- app/views/system_settings/_form.html.erb
- db/migrate/20200604102243_add_confirmation_page_text_fields_to_system_settings.rb
- db/schema.rb
Confirmation/thank_you page is the one they get taken to after submitting a Contribution
- (there's some things to think abt here as far as if it should be the same page after submitting a Community Resource, and, if Announcement submission should follow suit as well)
- Added fields so users can update confirmation page text: 
header, body, link_header ("check these out" links section), and footer
TODO: 
- This maybe needs to have more options to handle text specific to their `exchange_type`
- Def need to make sure this is all translatable w Mobility
> Add fields so confirmation page is configurable

- app/blueprints/configuration_blueprint.rb
The association was dropped from `ServiceArea` as a result of a00e5ce.
Ask and Offer forms are broken w/o this fix.
> Hotfix: drop text_translations reference in ConfigurationBlueprint

- app/javascript/components/NavBar.vue
Fixes #239 
This was a small fix. The reason for the behavior was the path was originally a relative path (so it works on the `root_path` but not elsewhere) and it needed to be an absolute path. I added the slash prefix, which does that. 
Tested manually.
> [239] | Fix sign-out so it 

- app/controllers/organizations_controller.rb
- app/views/devise/sessions/new.html.erb
- app/views/organizations/_form.html.erb
- db/migrate/20200604210255_add_logo_url_to_organization.rb
- db/schema.rb
- Add logo_url and favicon_url fields to Organization
- On login page, if the @current_organization.logo_url exists, display it instead of default system logo
TODO:
- Make favicon editable as well
- Make @current_organization available on vue side so navbar icon can be adjustable as well
> Add logo_url and favicon_url to organization for edit by admins

- package.json
- yarn.lock
Heroku deployment was failing on 'sass-loader'. 
LOTS of research and trying led @h-m-m and I to @crsexton's SUPER helpful article(s): https://www.codeography.com/2019/08/02/rails-6-on-heroku.html
Still, we couldn't get it to work. THEN, @crsexton paired w me just now for 1.5hrs and we determined that really really really, all we needed to do was move sass-loader out of the dependencies section of `package.json`. Well, that and correctly deploying the **branch** to heroku... (And maybe this helped too? `heroku plugins:install heroku-repo;  heroku repo:purge_cache -a [app name]`)
> Fix sass heroku error

- app/blueprints/configuration_blueprint.rb
- db/seeds.rb
Only LocationType.visible should display on Forms
- add visible scope to LocationType
- change LocationType seeds so all except 'service_area' are set to `display_to_public: true`
> Add visible scope to LocationType for display on Forms

- app/models/ask.rb
- app/models/browse_filter.rb
- app/models/offer.rb
- spec/factories/matches.rb
- spec/models/ask_spec.rb
- spec/models/browse_filter_spec.rb
- spec/models/offer_spec.rb
Completes #466 
Contributions page should only display `unmatched` contributions. Applying this child-model-level scope properly filters the list.
Idk how/where to write a test for this. Would love help! Ok to merge in the meantime so users are able to see only the "to do" list on Contributions page?
> Add unmatched scope to Ask/Offer before pushing to Contributions page

- app/controllers/admin_controller.rb
- app/controllers/contributions_controller.rb
- app/helpers/application_helper.rb
- app/models/person.rb
- app/views/admin/dispatch_steps.html.erb
- app/views/admin/landing_page.html.erb
- app/views/admin/volunteer_admin.html.erb
- app/views/communication_logs/_form.html.erb
- app/views/contributions/respond.html.erb
- app/views/contributions/triage.html.erb
- app/views/matches/_communication_history.html.erb
- app/views/matches/edit.html.erb
- config/routes.rb
After several trainings, it's clear the "Dispatch Steps" and associated pages needed to be a bit clearer.
- Respond page now has a link to Dispatch Steps at top
- Communications log is now on LEFT so it will match what's expected for an Ask once you transition to "Add a tentative Match" (Respond will most often be used for Ask workflow)
- Added "triage" action to ContributionsController to handle title/description updates (this may or may not be replaced by Submission Edit)
- Moved Communications history and Other Contributions & Matches almost below the fold
- Change some partials and helpers to improve design/UX
- Change admin endpoint urls to include admin prefix
> Redesign respond workflow

- app/javascript/components/forms/CategoryFields.vue
- app/javascript/pages/Ask.vue
- app/javascript/pages/Offer.vue
- spec/javascript/components/forms/CategoryFields.spec.js
- spec/javascript/pages/Offer.spec.js
Just a UI change for now, but sets us up to append add-on fields to subcategory checkboxes.
Note that the form will append the parent category tag to the submitted tags if any subcategory is selected.
Any parent category with no subcategories will show a faux subcategory with the same name, id as the parent.
> Turn parent categories into accordions on Ask/Offer forms

- app/controllers/admin_controller.rb
- app/controllers/form_questions_controller.rb
- app/models/custom_form_question.rb
- app/views/admin/form_admin.html.erb
- app/views/admin/landing_page.html.erb
- app/views/form_questions/edit.html.erb
- app/views/form_questions/index.html.erb
- app/views/form_questions/new.html.erb
- app/views/form_questions/show.html.erb
- config/routes.rb
There wasn't a way to access the form mgmt pieces of the app before
- Added indexes to admin_landing
- Created form_admin page where form-related indexes are
- Later prob want to add stats re which forms are live, how many responses, etc
- Added explicity type: :string for translations
- Update form-related views w app conventions like view_header
> Add form_admin and cleanup views

- app/models/custom_form_question.rb
Heroku yelled at me for having a scope named 'name' on CustomFormQuestion
> Rename scope on CustomFormQuestion

- .gitignore
- ORIENTATION.md
- README.md
Just a minor change from getting myself setup- `rake dev:setup` doesn't exist but `rake db:setup` does so I assume that's what goes here. The env variables are needed to get `db:setup` to run because otherwise `seed.rb` fails. 
I added the gitignore lines because of my local dev setup
Add a badge for the CI build to make it easier to find on the main page
> Improve readme setup instructions

- .release-it.yml
- CHANGELOG.md
- package.json
- yarn.lock
[release-it](https://github.com/release-it/release-it) automates the following tasks:
1. Selecting type of release (patch, minor, major)
1. Updating the `version` property in `package.json`
1. Generating a Changelog (see below)
1. Creating a commit with the `CHANGELOG.md` and `package.json` changes
1. Creating a tag for the new version
1. Pushing up to `origin`
1. Generating a github release with the contents from the changelog (WIP).
In this branch, we are using the [`keep-a-changelog` plugin](https://github.com/release-it/release-it/blob/master/docs/changelog.md#keep-a-changelog) which assumes we are managing the changelog manually, instead of dumping all commit messages since the last release.
The workflow would therefore be:
1. Manually update the `Unreleased` section of the changelog …
> Add release-it library to help automate release tasks

- app/views/layouts/_head.html.erb
Vue styles (currently limited to TileListItem.vue) aren't included in the main assets bundle, so we need to add a `stylesheets_pack_tag` to the head in order to load them from `public/packs/css`
> Add a stylesheet_pack_tag to include vue styles in prod

- .env
- .release-it.yml
- package.json
- yarn.lock
Also adds `dotenv-cli` package which lets us reuse `.env` and related files in node.
> Let release-it generate github releases

- CHANGELOG.md
- app/javascript/pages/browse/TileListItem.vue
* Move time to top of text section
* Make text black
* Shorten time display (don't need milliseconds 00:00:00)
* Remove 'Submitted: ' and 'Service Area:' text from cards 
* update CHANGELOG
After:
Before:
> Improve contributions readability

- package.json
Heroku expects this to be set, to determine which version of node to use. Currently this is the default anyway, but we should probably be explicit so that nothing changes if they update the default.
> Specify node version in engines

- CHANGELOG.md
Changes format to put issue, pr numbers _after_ the descriptive text.
While it was nice to have all the numbers aligned on the left, that scheme breaks a bit when we want to list multiple issues/prs. 
Moreover, i want to highlight _what_ the change was; the links are details that viewers can dig into if they choose, not the primary subject.
> Tweak changelog item format

- CHANGELOG.md
- app/views/matches/index.html.erb
There was a bug in Matches index where having a bunch of tags was causing table to be too wide
Now iterating over tag list and displaying each tag independently
(This will be less of an issue after Listings only have one category per tag)
Before:
After:
> Display tags independently on Matches index

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/categories.scss
- app/controllers/categories_controller.rb
- app/views/categories/index.html.erb
- On categories index, nest child categories below root (parent) categories and display rows in greyscale
After:
Before:
> Show nested categories differently in categories index

- app/views/community_resources/_form.html.erb
- app/views/listings/_form.html.erb
- app/views/submissions/show.html.erb
- Some imported data will need manual Listing creation. This allows users to easily add associated Listings.
- Added style override for tag_lists that are too long
Before:
After:
> Add create Ask and Offer buttons to submissions

- CHANGELOG.md
- app/controllers/submission_response_imports_controller.rb
- app/jobs/submission_response_import_job.rb
- app/models/importers/base_importer.rb
**Important**: this implementation has two major limitations:
1. Uses the `:async` queue backend which is in-memory only and isn't usually recommended for production. For now, to support imports only which typically happen before an installation is live, it might suffice. It does have the distinct advantage of not needing any additional infrastructure
2. Passes the _whole_ uploaded file contents into the background job as a string. This will obviously not scale and we'll have to monitor how feasible this is.
Resolves #585.
> Implement in-memory ActiveJob to background response import

- CHANGELOG.md
- app/blueprints/category_blueprint.rb
- app/blueprints/configuration_blueprint.rb
- app/models/category.rb
- All subcategories for any visible Category were displaying, but the visible scope needs to be applied to subcategories as well
> Only show visible subcategories on forms

- app/controllers/submission_response_imports_controller.rb
- app/javascript/components/forms/FileUpload.vue
- app/javascript/entry_points/fileUpload.js
- app/javascript/entry_points/index.js
- app/views/submission_response_imports/new.html.erb
Converts the upload UI in `submission_response_imports/new` to Buefy, introducing a potentially reusable `FileUpload` component.
Note: `Import` button shown above is not part of the component and comes from the enclosing form.
> Introduce FileUpload vue component and EntryPoint

- CHANGELOG.md
- app/blueprints/form_blueprint.rb
- app/blueprints/question_blueprint.rb
- app/controllers/asks_controller.rb
- app/controllers/offers_controller.rb
- app/controllers/submissions_controller.rb
- app/forms/submission_form.rb
- app/forms/submission_response_form.rb
- app/javascript/components/forms/CustomQuestions.vue
- app/javascript/components/forms/index.js
- app/javascript/pages/Ask.vue
- app/javascript/pages/Offer.vue
- app/models/custom_form_question.rb
- app/models/form.rb
- spec/factories/custom_form_questions.rb
- spec/factories/submission_responses.rb
- spec/forms/submission_form_spec.rb
- spec/javascript/components/forms/CustomQuestions.spec.js
- spec/javascript/pages/Offer.spec.js
Allow users to add CustomFormQuestions to Forms (and answers stored in db as SubmissionResponses)
- Currently only handles adding/storing 'string' questions. Still need to add support for boolean, date, etc, as well as support option lists so admins can provide data to populate a dropdown rather than having only text inputs.
- Tests re re updating a Submission were failing, and we've marked them as pending since we don't currently have that feature deployed anyway
> Custom form questions

- app/controllers/public_pages_controller.rb
- app/models/organization.rb
- app/views/layouts/_navbar.html.erb
- spec/requests/listings_spec.rb
- spec/requests/public_pages_spec.rb
- Change current_organization from a scope to a class method, since it's not returning a collection
- Add some let statements to tests
- Add some conditionals for when current_organization isn't present (in the wild, we *do* want to always have one)
> Handle current_organization errors in tests

- CHANGELOG.md
- app/models/listing.rb
Bug reported by @smoores
Fix:
* Remove final & operator so all nils -> 0.0
> Remove final & operator so all nils -> 0.0

- .rspec
- app/forms/submission_form.rb
- app/forms/submission_response_form.rb
- spec/forms/submission_form_spec.rb
Required looking up existing submission_responses by custom_form_question_id.
> Fix pending specs for SubmissionForm updating

- docker/production/docker-compose.yml
Adds some default logging configuration for the prod docker-compose setup, and allows configuration (with fallbacks) for POSTGRES_USER and POSTGRES_DB (I accidentally opened that first PR with hard-coded Tompkins County values)
> Logging and Configurable Postgres settings (docker-compose)

- CHANGELOG.md
- app/blueprints/submission_blueprint.rb
- app/controllers/asks_controller.rb
- app/controllers/offers_controller.rb
- app/forms/listing_form.rb
- app/forms/submission_form.rb
- app/javascript/components/forms/CategoryFields.vue
- app/javascript/pages/Ask.vue
- app/javascript/pages/Offer.vue
- app/models/category.rb
- spec/forms/submission_form_spec.rb
- spec/javascript/components/forms/CategoryFields.spec.js
- spec/models/category_spec.rb
Changes `SubmissionForm` and `ListingForm` to generate a Listing per category selected.
This includes a change to send category ids on form submission instead of tag names. See commit 4fcdc05 for rationale and consequences.
Doesn't include any changes to the UI (that will follow subsequently).
Closes #536 
Co-authored-by @maebeale.
> Generate one Listing per category on form submission

- CHANGELOG.md
- Changelog had the header `## Unreleased`, but it needs to have brackets  (`## [Unreleased]`) for releaseit to work
> Change header in changelog so releaseit will work

- CHANGELOG.md
- README.md
Not sure if there's actually anything more to change in code.
* Didn't find any reference to `master` in our CircleCI config (~we'll see how this PR does~ all good!).
* No mention of it in our deployment docs either, but i'm not sure if that's definitive?
There's probably more to do on GitHub itself but i don't have privileges to see those settings, @maebeale ?
Also went through and changed the base branch of all existing open PRs.
For developers, this change should be pretty simple to absorb:
* `git fetch && git switch main`.
* Rebase any local branches onto `main`.
* Or merge into/from `main`.
> Switch to `main` branch!

- CONTRIBUTING.md
- README.md
- SEEDING.md
- TESTING.md
See commit messages below for a list of the high level changes.
Probably also easier to review the commits separately.
Though, TBH, an even better way is probably to click around the branch tree itself:
https://github.com/rubyforgood/mutual-aid/tree/further-readme-edits.
> Further readme edits

- lib/tasks/db.rake
- spec/requests/contributions_spec.rb
Ran into a case where the id conflicted with an existing record in the test db (possibly from a seed).
> Don't rely on fixed ids in contributions_spec

- app/models/html_sanitizer.rb
- spec/models/html_sanitizer_spec.rb
Add b, h{1,2,3,4,5,6}, and span to allowed tags in the HTMLSanitizer model
Also add a spec file for this (not all methods and allowed attributes are tested)
Addresses https://github.com/rubyforgood/mutual-aid/issues/663
> Add more tags to the HtmlSanitizer allow list

- docker/development/app/Dockerfile
Was resulting in an error when attempting to run the build:
app_1    | /usr/local/bundle/gems/thor-1.0.1/lib/thor/parser/arguments.rb:133:in `parse_numeric': Expected numeric value for '--port'; got "${APP_PORT}" (Thor::MalformattedArgumentError)
There are two things that aren't quite set up right here:
The build arg was not in scope -- used args need to be _below_ the
`FROM` statement to be accessible.
CMD appears to not allow variable expansion, because it is processed at
runtime rather than build time.  Instead, we can export the `PORT`
envar, which will be picked up by `config/puma.rb` when starting rails.
> Fix docker buildfile

- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Resolves #518 
We want to ensure that all pull request made to this repository follow a uniform pattern. This will make it easier to review new pull requests. It will also help to promote cultural norms around testing and security/accessibility mindfulness.
A github pull request template is a simple markdown document, placed in the special `.github/PULL_REQUEST_TEMPLATE` directory. Github will use files in these folders to give users the option to use the template when creating new pull requests.
You can find more information in [github's documentation](https://docs.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository). This template was also inspired by the [casa …
> Create a new pull request template

- app/controllers/announcements_controller.rb
- app/controllers/community_resources_controller.rb
- app/controllers/public_pages_controller.rb
- app/controllers/system_settings_controller.rb
- app/views/system_settings/_form.html.erb
- app/views/system_settings/show.html.erb
- db/migrate/20200906172102_add_display_navbar_to_system_settings.rb
- db/schema.rb
- db/seeds.rb
The issue is attached - there needs to be an option as to whether the navbar should show up on the Community Resources and the Annoucements pages. So I added an option for that in system settings that can be toggled. 
Question: 
the lists /annoucements-list and /community-resources-list are both handled by PublicPagesController, so I added the same method in there as well but I am not sure if that was intended or not (last commit)
Also should index also have the display_navbar switch or should it always be without_navbar?
> Option to display navbar

- docker/development/Makefile
There's no need to run the test service when booting the application
for development via docker and Make
> Only start development services by default via make

- doc/setup.md
- docker/development/Makefile
Before, any one-off container made by these make tasks hangs around in
an exited state after command execution is terminated - notice
`development_app_run_e3b196b37f5d` in the example below:
```
[maximilian: development] cleanup-one-off-development-containers *^ →
$ make rspec
docker-compose run app bin/rspec
...snip...
Finished in 36.48 seconds (files took 11.52 seconds to load)
286 examples, 0 failures, 177 pending
Randomized with seed 34516
[maximilian: development] cleanup-one-off-development-containers *^ →
$ docker-compose ps -a
Name                            Command               State                 Ports
-------------------------------------------------------------------------------------------------------------
development_app_run_e3b196b37f5d   bin/rspec …
```
> Cleanup one-off development containers created via make

- lib/tasks/one_time.rake
- lib/tasks/support/listing_converter.rb
- spec/lib/tasks/support/listing_converter_spec.rb
This got complicated when we started to consider sub-categories!
See af063eca12d82ded8a2568d1c61a54320b7b60e2 for my attempt to deal with them. I'm not sure how well the code speaks for itself; happy to get on a call if that would be easier/better.
The `one_time:split_listings` rake task _should_ be idempotent on repeated runs, though it will always have to pull and examine any listings with sub-categories (since the query looks for any listing with multiple tags). I formatted the `puts` output to be csv compatible with 3 columns:
1. an indicator for visual scanning (`#` - listing being processed, `-` listing after processing, `+` newly created listings),
1. the listing id (original or new),
1. tag_list
Will definitely need some 👀 to verify my specs/logic and do some more testing.
> Migrate multi listing submissions

- bin/dev/bootstrap
- bin/dev/clean
- bin/dev/console
- bin/dev/serve
- bin/dev/shell
- bin/dev/stop
- bin/dev/test
- config/database.yml
- docker/development/app/Dockerfile
- docker/development/docker-compose.yml
Fixes `ActiveRecord::EnvironmentMismatchError` after a
`bin/dev/bootstrap` and `bin/dev/test`.
TLDR; The `development` and `test` environments were sharing the
`mutualaid` database instead of being isolated in their own databases.
References
----------
- #718
> Fix environment mismatch error in docker env tests

- app/javascript/pages/Browse.vue
- app/javascript/pages/browse/Filters.vue
This PR makes `/contributions` filters [collapsible](https://buefy.org/documentation/collapse)
> Make filters collapsible fixes #724

- Gemfile
- Gemfile.lock
Newer version of puma is easier to build on a fresh box.
> Upgrade puma, mostly to simplify dev setup

- .env
- docker/development/docker-compose.yml
This is intended temporarily silence deprecation warnings emitted from
third-party gems that have yet to become compatible with Ruby 2.7.0.
This is somewhat dangerous if left in long-term as warnings use of
soon-to-be-removed language features by the application itself will be
silenced.
This should be removed before the next time this code base upgrades
Ruby.
**NOTE**
This does NOT silence Rails deprecation warnings, these
should probably be addressed independently - a quick eyeball survey
shows that most of the Rails deprecation warnings are addressable in
the application code.
References
----------
- https://github.com/rubyforgood/mutual-aid/issues/718
> Silence Ruby 2.7.0 deprecation warnings

- app/assets/stylesheets/bulma_and_buefy.scss
- app/javascript/components/MappedIconList.vue
- app/javascript/pages/browse/BrowserSelector.vue
- app/javascript/pages/browse/ListBrowser.vue
- app/javascript/pages/browse/TileListItem.vue
- spec/javascript/pages/Browse.spec.js
Updates the contributions view layout for browse (tile|list|map) buttons, tiles and list view items. Relates to #282. 
Update layout based on [contributions mocks](https://github.com/rubyforgood/mutual-aid/issues/707#issuecomment-697109318)
Navigate to the `/contributions` view and visually inspect
> Cleanup contributions view

- docker/development/docker-compose.yml
In a docker development environment, the test are run using the app
service - IE the use the same "image" as the running application - via
bin/dev/test. This service is no longer needed.
Resolves #739 
`bin/dev/test` reuses the `app` service's image to spin up a container in which the tests are run. For `rspec`, the spec_helper already specifies that the application will run in the `test` environment, rather than the default.
`bin/dev/test` should still run the test suite
It might be nice to provide an interface to allow the developer to run a specific, or subset, of examples/specs in the test suite. I know this fuctionality exists via RSpec, but the `bin/dev/test` script currently assumes that you want to run …
> Remove unused test service

- app/javascript/pages/browse/MapBrowser.vue
An error showed up in the web console when the map attempts to access `contribution.location.street_address` when `contribution.location` is null. This fix addresses that.
> Fix accessing null location

- doc/setup.md
My first pass at documenting how to use the Docker development environment imparts a feeling of importance on certain less important parts of the setup. This seeks to clarify that the binstubs are shorthand helpers to get up and running quickly or make broad strokes across the codebase. As it stands now `bin/dev/shell`, and `bin/dev/serve` are probably the tools with which developers will want to interact. This elevates their place in the docs and adds some additional uses, warnings, etc. 
> Enhance docker development docs

- .env
- CHANGELOG.md
- app/views/submission_mailer/_generic_confirmation_email.html.erb
- config/application.rb
- config/environments/development.rb
- config/environments/production.rb
- config/environments/test.rb
- doc/setup.md
- docker/development/docker-compose.yml
Fixes `mailcatcher` setup for local (non-docker) development and introduces several related refactorings.
I believe our mailcatcher setup broke in a recent change and was trying to connect to sendgrid. This went unnoticed because we were testing from the local docker env, where the smtp host/port are configured to point at the `email` service.
Also includes these related changes:
* Rename SMTP_ADDRESS env var -> SMTP_HOST, 56d0286
Since it deals with email addresses, i found the existing variable name to be confusing. Host is also more commonly used, alongside port.
* Remove unimplemented reference to `SystemSetting#hybrid?`, 10a8766
This was breaking the new submission mailer.
* Consolidate smtp config between dev and prod, 81e37bb
All the relevant settings are configured via environment …
> Fix mailcatcher for local development

- .github/pull_request_template.md
The pull request template marks certain sections as optional, implying the others are mandatory. As i've been using the template, i'm finding that some of the sections don't make sense in all contexts.
This removes mentions of optionality, hopefully giving authors more agency in choosing what to include and what to ignore. The template is already quite long and i'm worried about it being overwhelming and therefore being ignored over time or not taken seriously; this is an attempt to signal that it's more a guide and set of reminders than a mandate.
Curious your thoughts in particular @grenewode
> Tweak pull_request_template to signal more leeway on what to include

- Gemfile
- Gemfile.lock
`guard` with [`guard-rspec`](https://github.com/alexch/rerun) is a fine solution but presented a few imperfections:
1. It would slow down over time; every automatically triggered run would take slightly longer.
1. By default it uses a 1 to 1 mapping of spec to app code. This is often a good choice, but i often want to run a _set_ of specs as i make related changes. This is difficult to achieve with guard.
1. It has a non-trivial configuration scheme. This is not often a problem since plugin gems usually generate configuration for us, but when we do need to tweak something, there's a significant api to learn.
[`rerun`](https://github.com/alexch/rerun) is a much simpler tool that addresses all of the above.
I'm not aware of any core/recent contributors using guard, but if anyone is, we can …
> Replace guard with the much lighter rerun gem

- bin/dev/bootstrap
Currently, `bin/dev/bootstrap` only builds the `app` image and when we run `bin/dev/serve` or other dependent command, the `webpack` and `email` images are built. While there's value in building these 'just-in-time', i'd prefer bootstrap build all three images.
This will surface any issues when a user first sets up their docker env and subsequent commands will fire up more quickly.
Tested locally but would love another set of eyes to verify.
* The `dc` function in `bin/dev/bootstrap` uses the `$@` variable which seems to work but is new to me; is this an approprate use? Are there any gotcha's with it?
> Enhance docker bootstrap to also build webpack, email images

- bin/dev/bootstrap
- docker/development/app/Dockerfile
- docker/development/docker-compose.yml
The current Docker-based development setup essentially does the same things multiple times to produce images for the `app` and `webpacker` services. The goal of this body of work is to produce images for these services and allow the to reuse existing, cached artifacts to prevent the build phase from doing unnecessary work. 
The docker-compose setup includes a persistent volume intended to serve as a cache for bundler and rubygems. However, the volume mount contains a small error which is causing gems to be installed on the ephemeral filesystem - IE the gem cache is lost when a container exits. This means that every request to start an app container needs to re-install rubygems - and therefore re-run every step that comes after in the Dockerfile. This leads to longer than necessary wait …
> Fix multiple image builds when starting docker

- doc/setup.md
Adds a bit more instruction for anyone installing `asdf` for the first time.
No review necessary.
> Document asdf setup for fresh installs

- CHANGELOG.md
- app/controllers/registrations_sans_signup_controller.rb
- config/routes.rb
Since #660 was fixed, users can now sign themselves up, but we don't have working authorizations so any new user would have sys-admin privileges.
To avoid this, we are temporarily disabling sign ups. They were actually broken in previous releases, so this change effectively maintains the current behavior.
This work can be reverted once #514 is merged.
- New controller that overrides `Devise::RegistrationsController`, giving notice to the user that sign ups are disabled.
- Based on [this SO solution](https://stackoverflow.com/a/8291318)
See why section above.
> Disable user sign_up until pundit work is ready

- CHANGELOG.md
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/custom_text.scss
- app/javascript/pages/orientation/AboutSection.vue
- app/views/contributions/thank_you.html.erb
- app/views/public/about.html.erb
Fixes #777, where unordered lists weren't rendering with discs in user-provided custom text.
Also sets up a container class for future styles that need to be applied to all custom text.
Before:
After:
Introduced a new `custom_text.scss` file defining a `.custom-text` class.
This class needs to be applied to any element that contains user provided content.
Could be worth considering what other styles we want to apply to custom text (eg, what about `ol`s?).
Co-authored-by: maebeale <meabeale@gmail.com>
> Start of css to be applied to all custom text (user submitted)

- db/seeds/dev_seeds.rb
- lib/tasks/db.rake
Closes #719, since sometimes the seed would not perform successfully.
In favor of having consistent environments, I took the liberty to replace the sequence `db:drop db:create db:migrate` with `db:reset db:migrate`. This ensures consistency between environments and avoids running all the migrations (this could go bad easily). More notes in c69a95a.
Besides that, I also added `db:seed` to `import_all_seeds` to always seed the base, and then the development environment, which fixes the exception regarding an undefined method, and I added an `&` in case something else happens.
In the other hand, the bug mentioned at #719 regarding password length, I added a prefix, more notes at 9aecf92.
Didn't add any testing for this.
I see a lot of opportunities to improve the seed files, both …
> Fixes db seeds rake tasks for development

- app/controllers/public_pages_controller.rb
- app/models/html_sanitizer.rb
- app/views/contributions/thank_you.html.erb
- app/views/public/landing_page.html.erb
- spec/models/html_sanitizer_spec.rb
Found a bug with single-quotes in the custom regex we'd written and while looking into this, realized we probably don't need a separate sanitizer for vue. We were able to get the only current use of this method (on the landing page) to work with sanitize_for_rails along with regular serialization (.to_json).
Refactored `HtmlSanitizer` class to drop `sanitize-for-vue` and rename `sanitize-for-rails` -> `sanitize`.
We're still running user content through `sanitize`. In fact, this is probably more secure now that we're not relying on a custom regex for sanitization.
Co-authored-by: maebeale <maebeale@gmail.com>
> Remove sanitize-for-vue

- app/interactions/email_new_submission.rb
- app/models/communication_log.rb
- db/migrate/20201113172851_allow_null_communication_logs_created_by_id.rb
- db/schema.rb
- spec/interactions/email_new_submission_spec.rb
Fixes #805.
Integrating `EmailNewSubmission` into `Asks|OffersController` broke those forms for anonymous users. `CommunicationLog.log_email` allows a nil `initiator` object but the DB does not allow null in the corresponding `created_by_id` column.
First, the `EmailNewSubmission` interactor needed to allow a nil user (for when `current_user` is `nil`). But this by itself was not sufficient because the nil then causes `PG:NotNullViolation`.
`communication_logs.created_by_id` did have a default id set to 1, but this requires persistence code to omit the `created_by` field if it isn't provided; if a write is issued containing `created_by: nil`, rails will pass that on to the DB which then rejects it.
Moreover, i don't think it's wise to assume our 'system user' will always have an id of 1. …
> Allow anonymous users to generate CommunicationLogs

- app/assets/stylesheets/font_awesome.scss
- app/javascript/components/MappedIconList.vue
- app/javascript/components/SingleIcon.vue
- spec/javascript/components/MappedIconList.spec.js
Co-authored-by: Leah Riffell <leah.riffell@gmail.com>
Co-authored-by: Angela Guardia <47278429+AngelaGuardia@users.noreply.github.com>
Co-authored-by: David Atkins <atki1080@gmail.com>
Co-authored-by: Taylor Phillips <taylorscottphillips@gmail.com>
Co-authored-by: Nathan Darrington <npdarrington@icloud.com>
Co-authored-by: Eugene Theriault <hybridbassist@gmail.com>
Co-authored-by: Will Dunlap <dunlapww@gmail.com>
closes #391 
Add fab class to fix whatsapp logo display
Icon now works both on the Vue side (/contributions), and on the rails side (/contact_methods)
Font awesome requires fab class to display brand icons
Imported font awesome brand
Added fab class to the whatsapp icon of SingleIcon.vue and MappedIconList.vue
Added a test that whatsapp label exists and fab class exists
> Add fab class to fix whatsapp logo display

- CHANGELOG.md
- app/javascript/pages/browse/MapBrowser.vue
Fixes #753, since the initial map view was not displaying all the offers.
Regarding the CHANGELOG, not sure if I should do it. Please advice.
- Uses bounds extender with processed markers in order to have all bounds and fit the map
- Uses padding to avoid cutting off the icons (see screenshot attached)
It uses [LngLatBounds](https://docs.mapbox.com/mapbox-gl-js/api/geography/#lnglatbounds) and it's method `extend` in order to have a bound box that later can be set to fit the map.
N/A
N/A
N/A
N/A
N/A
> Fit all the offers in the initial view for the map

- app/javascript/pages/browse/Filters.vue
- spec/javascript/pages/browse/Filters.spec.js
Resolves #756. 
I added the ability to check all/uncheck all filters by column as well as the entire filters section. If any of the filters in the column is checked, the checkbox for select all shows an indeterminate state. 
I guess the code is pretty self-explanatory, I tried to keep it simple. I added toggle functions and some helpers to detect the state of the checkboxes.
I changed the behavior of the old test a little bit because there are more checkboxes now. I am not a frontend developer, this is my first time writing tests for Vue, I tried to follow the example of an existing test. I guess the next step is to add more tests for the functionality I created, for example, test indeterminate state of checkboxes, test for toggle functions. I think the tests I added are not good enough …
> #756 User is able to select filters quickly

- app/controllers/contributions_controller.rb
- app/models/browse_filter.rb
- spec/requests/contributions_spec.rb
This is one of the required steps of the peer-to-peer matchmaking workflow. This makes the list of available contributions generally public if the peer-to-peer setting is on.
The next step after this will be to change what the "Respond" button does for people who aren't logged in. I'd prefer to keep that next step in a separate PR, but can add it on to here if people would rather keep them together.
Also, the permission logic here should be refactored out to a Pundit object once we're bringing those in. @maebeale talked about adding features later that allow users to mark their contributions as "for admin eyes only" or something similar. Implementation of those features would be a good time to refactor here.
I expect this change will have no net effect on accessibility excepting any of …
> View contributions publicly when peer-to-peer is on

- app/controllers/contributions_controller.rb
Was mistakenly dropped in e301ccd9, but is necessary even in dispatch mode so that guests can create contributions.
https://user-images.githubusercontent.com/8330/104955888-f7aad080-5998-11eb-9b62-1a3986e3c4d0.mov
> Restore ability to hit /thank_you page w/o logging in

- CHANGELOG.md
- app/controllers/contributions_controller.rb
- app/javascript/components/NavBar.vue
- app/views/layouts/_navbar.html.erb
- spec/javascript/components/NavBar.spec.js
We want to show the /contributions link in navbar when p2p enabled because it's a key part of the p2p workflow
Screenshots of current code:
Logged out with P2P
Logged out without P2P
Logged in
We're adding a prop passed to Vue that indicates if P2P is on or not, and then letting Vue show or hide the button
There are some JS tests since this is mostly a JS change
We talked some about rearranging these. Our concerns were:
- arranging buttons so items of higher priority or higher usefulness stand out more, which changes depending on context
- if someone logged in trying is to give instruction to someone not logged, it should be easy without the logged in person having to memorize which buttons are and are not the same for the logged out person
- having order be consistent and predictable
- …
> Show /contributions link in navbar when p2p enabled

- app/controllers/claims_controller.rb
I introduced a regression in 7fa64948 by not accounting for params being nested under `params[:claim]` 🤕 
Really speaks to the need for integration tests!
> Fix missing params error when claiming

- CHANGELOG.md
- app/controllers/contributions_controller.rb
- app/javascript/pages/browse/ListBrowser.vue
- lib/contributions.json
- spec/javascript/pages/browse/ListBrowser.spec.js
- spec/requests/contributions_spec.rb
This addresses one of the items in #819
We'll probably want more logic involved later. For now, it's okay hide all "respond" UI items when not logged in. The only time they should show up for users not logged in is when the system is in peer-to-peer mode
Also, I added some tests, pulling some test data from my dev environment
When not logged in, viewing tiles:
When not logged in, viewing the list:
When logged in viewing tiles:
When logged in viewing the list:
The two key changes are 
- a line in the controller that makes the respond link conditional
- a line in the list view that hides the "Respond" header of no controllers have data for it
This should not change accessibility as it makes an existing UI element entirely hidden conditionally
This is pretty reasonable, security-wise. The …
> Hide the "respond" UI items when not logged in

- app/controllers/admin_controller.rb
- app/controllers/contact_methods_controller.rb
- spec/requests/admin_authorization_spec.rb
Before we open up user registration, we have to secure any pages that should only be accessible to admins (sysadmins). This actually turns out to be the vast majority of our controllers, so ideally we can solve this w/o a lot of drudge work.
* With `pundit`, we would usually `authorize` each action independently and create policy classes for each resource.
* For admin-only resources, this seems like overkill: these controllers and actions all require exactly the same check.
* Inheriting this logic from a base controller in the form of a `before_action` seems like a simpler solution.
* Currently, `AdminController` contains a bunch of non-restful actions. I recommend we extract them out into their own controllers so `AdminController` can become an abstract base class.
Added a spec …
> Solution to secure admin-only resources

- app/controllers/categories_controller.rb
- app/controllers/communication_logs_controller.rb
- app/controllers/custom_form_questions_controller.rb
- app/controllers/donations_controller.rb
- app/controllers/feedbacks_controller.rb
- app/controllers/form_questions_controller.rb
- app/controllers/forms_controller.rb
- app/controllers/history_logs_controller.rb
- app/controllers/listings_controller.rb
- app/controllers/location_types_controller.rb
- app/controllers/locations_controller.rb
- app/controllers/matches_controller.rb
- app/controllers/mobility_string_translations_controller.rb
- app/controllers/organizations_controller.rb
- app/controllers/positions_controller.rb
- app/controllers/service_areas_controller.rb
- app/controllers/shared_accounts_controller.rb
- app/controllers/shift_matches_controller.rb
- app/controllers/shifts_controller.rb
- app/controllers/software_feedbacks_controller.rb
- app/controllers/submission_response_imports_controller.rb
- app/controllers/submission_responses_controller.rb
- app/controllers/submissions_controller.rb
- app/controllers/system_locales_controller.rb
- app/controllers/system_settings_controller.rb
- app/controllers/teams_controller.rb
- app/models/listing.rb
- spec/requests/listings_spec.rb
Gives all admin-only controllers rudimentary authorization by inheriting from `AdminController`.
See #835 for background.
This is part of the work to re-open user registration.
Once all that work is ready, we'll need to do some extensive manual regression testing.
Most importantly, please check whether all these controllers are actually only for admin use.
?
?
> Add simple auth to all admin-only controllers

- app/controllers/application_controller.rb
- app/controllers/asks_controller.rb
- app/controllers/offers_controller.rb
- app/controllers/public_controller.rb
- app/controllers/public_pages_controller.rb
As we consolidate our authorization solution, there are a handful of controllers that are fully public and don't need authentication or authorization. This is codified in `PublicController`
See #840.
And once we're done with this push, it could be useful to review where we've landed with:
* `Authorization` concern
* `ApplicationController`
* `AdminController`
* `PublicController`
?
> Open fully public controllers

- app/controllers/claims_controller.rb
- app/controllers/concerns/authorization.rb
- app/models/user_context.rb
- app/policies/application_policy.rb
- app/policies/claim_policy.rb
- spec/policies/claim_policy_spec.rb
A lot of our policies will rely on `SystemSettings`. The [recommended way](https://github.com/varvet/pundit/#additional-context) to provide such additional context is to wrap a custom object around the `user` injected into policy initializers.
* Override `pundit_user` to provide a custom `UserContext` instead of a plain `User`.
* The `UserContext` is then decomposed in `ApplicationPolicy` so that the change is tranparent to sub classes.
* Add `ClaimPolicy` and `...Spec` as examples of accessing `SystemSettings` in policies.
We could instead have accessed `SystemSettings.current_settings` directly from any policies that need it. While that would certainly have been more straightforward, i preferred this solution for two reasons:
1. The solution here adheres to the Dependency Inversion …
> Introduce pundit user context

- app/models/listing.rb
- spec/models/listing_spec.rb
Improving user privacy by removing person name from the contributions map view
Addresses one item in #819 
-  prevent person name from showing on map view
Before
After
- Removed `(person.name)` from `listing.rb` `name` method
- No tests were added for this. Tested visually.
- The current solution may affect other views in the app where the person name is desired
- Instead of modifying the `name` method, I wanted to create a new method in `listing.rb` called `private_name` and call that on line 63 of `MapBrowser.vue`. That way I could be certain that this change would not affect other areas of the app. I wasn't able to make that work but it may be a better solution.
> Remove name in map view

- app/controllers/announcements_controller.rb
- app/controllers/application_controller.rb
- app/controllers/concerns/authorization.rb
- app/lib/user_role.rb
- app/models/context.rb
- app/models/user_context.rb
- app/policies/application_policy.rb
- spec/models/context_spec.rb
- spec/policies/claim_policy_spec.rb
This changeset was motivated by the proliferation of inherited @variables in many of our controllers, eg `@system_setting`.
It's bad practice to reference superclass instance variables because it creates very tight coupling up and down the inheritance chain. These variables essentially become globals.
In rails, this problem is usually solved in one of several ways. Taking `@system_setting` as an example:
* Wrap variables in attr_readers, eg `attr_reader :system_setting`. This is an improvement but still maintains coupling between super and sup classes.
* Mix in a module containing an accessor. This is an improvement because it doesn't force accessors onto other classes in the inheritance chain that don't need it. There are still a couple of downsides:
* There are usually a number of …
> Introduce context

- app/controllers/application_controller.rb
- app/models/context.rb
- app/policies/application_policy.rb
- app/policies/person_policy.rb
- app/policies/user_policy.rb
- spec/models/context_spec.rb
- spec/policies/application_policy_spec.rb
Rolls the `?admin=false` logic into `ApplicationPolicy` via `Context` introduced in #844.
This will allow us to eventually drop the `@admin_status` controller variable and cleanly rely on policies instead.
Also serves as an example of how `Context` is useful outside of the controller layer.
1. Adds a `admin_param` flag to Context, passed in from `ApplicationController`
1. Extract and use this in `ApplicationPolicy` to allow for `admin?` and `sys_admin?` privileges to be overridden by sending `?admin=false`
1. Adds new `can_admin?` methods to `ApplicationPolicy` and `Context`. This method tests whether the user is an admin or sysadmin and knows about the `?admin=false` url param override.
?
?
> Admin param

- app/javascript/components/NavBar.vue
- app/policies/nav_bar_policy.rb
- app/views/layouts/_navbar.html.erb
- spec/javascript/components/NavBar.spec.js
- spec/policies/nav_bar_policy_spec.rb
Required before we can re-enable user registration (#840).
```
NavBarPolicy
visible_buttons
guest
is expected to contain exactly "Login"
in peer_to_peer mode
is expected to contain exactly "Contributions" and "Login"
neighbor
is expected to contain exactly "Feedback" and "Logout"
in peer_to_peer mode
is expected to contain exactly "Contributions", "Feedback", and "Logout"
admin
is expected to contain exactly "Contributions", "Matches", "Admin", "Feedback", and "Logout"
sys_admin
is expected to contain exactly "Contributions", "Matches", "Admin", "Feedback", and "Logout"
// spec/javascript/components/NavBar.spec.js
NavBar
visible buttons
when not instructed to show additional buttons
✓ shows publicly accessible links
when instructed to show Contributions
✓ includes specified buttons
when …
```
> Show/hide buttons on NavBar based on user role

- lib/tasks/one_time.rake
Our recently merged pundit work correctly restricts all admin pages to users with `admin` or `sys_admin` roles. However up until now, _any_ logged in user on existing installations was effectively an admin.
To match that reality, this PR adds a rake task to set the `admin` role on any existing user whose role is unset.
Fixes #852
@maebeale :
* Does this change make sense? Are there existing users who shouldn't be 'promoted' like this?
* Should we cut a release with this patch?
* Are there other installations where this task will need to be applied?
> Add task to give existing users admin privileges

- app/controllers/claims_controller.rb
- app/interactions/claim_contribution.rb
- app/views/claims/new.html.erb
- spec/interactions/claim_contribution_spec.rb
The current claim page allow the logged in user to provide an alternate email address to be sent to the contributor.
This opens the door to potential abuse or mistaken use because we would pass along the overriden email without verifying it.
This changes the implementation to use the logged in user's email, giving them a link to change it if they want to.
Since user account emails are verified, we gain a level of confidence that we're not passing along bad/incorrect emails.
* Changed `spec/interactions/claim_contribution_spec.rb` to match new behavior.
?
?
> Don't allow email override when claiming a contribution

- app/views/contributions/_top_level_card.html.erb
- app/views/contributions/show.html.erb
Fixed the bad merge in 9de84a0d9f984120531227402f9e2124e1b58d00 in #846, moved the disabled claim logic into the new card
@leahriffell @AngelaGuardia - looks like this merge duplicated the cards. We went ahead and merged this but could you take a look to check that we brought everything over?
> moved disable claim logic/fixed merge

- app/controllers/community_resources_controller.rb
- app/models/community_resource.rb
- app/models/community_resource_service_area.rb
- app/models/service_area.rb
- app/policies/community_resource_policy.rb
- app/views/community_resources/_form.html.erb
- app/views/community_resources/index.html.erb
- app/views/community_resources/show.html.erb
- db/migrate/20210226012229_create_community_resource_service_area.rb
- db/schema.rb
- spec/models/community_resource_spec.rb
- spec/requests/community_resources_spec.rb
Co-authored-by: maebeale <maebeale@gmail.com>
Co-authored-by: exbinary <exbinary@gmail.com>
Co-authored-by: connieh1 <connie2630a@gmail.com>
Community Resource can have multiple service areas so we changed the relationship to be a many to many by creating a CommunityResourceServiceArea as a join
> changed service areas to be a many to many

- app/policies/announcement_policy.rb
- app/policies/application_policy.rb
- app/policies/claim_policy.rb
- app/policies/community_resource_policy.rb
- app/policies/glossary_policy.rb
- app/policies/nav_bar_policy.rb
- app/policies/person_policy.rb
- app/policies/user_policy.rb
- spec/policies/announcement_policy_spec.rb
- spec/policies/application_policy_spec.rb
- spec/policies/claim_policy_spec.rb
- spec/policies/community_resource_policy_spec.rb
- spec/policies/contribution_policy_spec.rb
Definite tradeoffs in both directions but after a group discussion, felt that new engineers having to investigate/learn another term wasn't worth the benefits of the explicit qualification.
1. Dropping back to `user` -- the term used in pundit docs/examples with the understanding that any _other_ users in play can be qualified as needed.
1. Rename a couple of related private methodes in `UserPolicy` and `PersonPolicy`
1. Also renames `original_scope` to `scope`. Doesn't feel like the qualification is necessary so falling back to the
term used in pundit docs/examples.
Note: this changeset builds on #833 which first drops some spec code that uses the same term.
We discussed that we'd love @bhaibel  to weigh in on this since she likely considered these tradeoffs. We'd ideally not merge these …
> Rename acting_user accessor in policies

- CHANGELOG.md
Added updated changelog history notes for all the awesome work that's been done this month!
* All users prior to this change now need to have their permission level set. Use the `make_users_admins` rake task to give existing users admin privileges #853
* Registration is now re-enabled! This isn’t breaking per se, but important to know that users can now self-register #840, #859
* Logged in users’ email is autopopulated when claiming a contribution (instead of letting them manually enter one) #855
* Claim button is disabled when p2p and no email related to contribution (because our system currently only sends notification emails) #846, #868
* Allow CommunityResources to have many ServiceAreas #870
* Show/hide buttons on NavBar based on user role #850
* Remove name in map view #847
* …
> Add changelog history from 2021-01-22 - 2021-03-03

- app/models/importers/submission_response_importer.rb
- db/seeds/dev_seeds.rb
`publish_from` & `description` is now mandatory in `Announcement` & `CommunityResource` models. Therefore,
`bin/rake db:rebuild_and_seed_dev` gets validation error and fails to run.
> Seed files need to be updated to reflect latest changes, and to run without validation error.

- app/mailers/peer_to_peer_match_mailer.rb
- app/views/peer_to_peer_match_mailer/peer_to_peer_email.html.erb
Co-authored-by: connieh1 <connie2630a@gmail.com>
Co-authored-by: maebeale <maebeale@gmail.com>
Autoemails sent after someone Claims a Contribution needed some framing text
We added a first pass of the Claim notification email template text
N/A
We should also consider sending an autoemail to the Claimer to confirm they did, in fact, Claim, and w note re that they should contact the mutual aid group if they don't hear back from their person within two days.
We prob will want to get out of this being a hard-coded option (or have an override).
> add claim email text for p2p

- config/environments/production.rb
Resolves bug with confirmation email is incorrectly linking to port 38076
We determined that this problem exists both locally and on production, the prod server is likely using a non-standard port (38076) and that is being added to the confirmation url by the following line in `config/application.rb`:
```
config.action_mailer.default_url_options = {
host: ENV['SYSTEM_HOST_NAME'],
port: (ENV['PORT'].presence || 80).to_i,
}
```
Setting the host without the port should resolve this issue.
There are currently no tests for this as it is a devise method, but this should be tested in a demo environment to ensure it works as expected.
Test in the demo environment
None
N/A
N/A
N/A
> Set default mailer url for production

- app/views/announcements/index.html.erb
Prior to introducing the presence validation on `Announcement#description`, several announcements were created in production without a description. This broke the announcement index page because there were a couple references that depend on a description present.
Fixes #888 
N/A
N/A
N/A
N/A
> [Bugfix] Use safe nav operator to handle nil descriptions on announcement index page

- config/webpack/environment.js
- package.json
- yarn.lock
It appears that #897 broke webpack compilation locally (dev, test), at least on my machine, failing with:
`Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (83)`
Some research led me to https://github.com/rails/webpacker/pull/2716 which has been merged into webpacker 6 but not backported into our current version.
This changeset manually overrides the sass-loader implementation from `node-sass` to `sass`, as described [in this article](https://mentalized.net/journal/2019/10/19/use-sass-modules-in-rails/).
Left a FIXME comment in `config/webpack/environment.js` to remove this workaround when we upgrade to webpacker 6.
?
> Fix local webpack compilation

- app/controllers/community_resources_controller.rb
- app/policies/community_resource_policy.rb
- app/views/community_resources/_form.html.erb
- spec/requests/community_resources_spec.rb
closes #879 
- **Previously**: when user creates new Community Resource, they must select from dropdown of addresses of existing Locations
- **Now**: when user creates new Community Resource, they input an address
- If Location with this address and type already exists, associates new Community Resource to this Location
- If Location with this address and type _does not_ exist, creates new Location and associates new Community Resource to this Location
Previously:
Now:
- Used `first_or_create` to find or create a new Location
- Updated existing request spec to add address params 
- Refactor into form object design pattern + add unit tests
- Want to add more testing - ex: new location vs. location already existing
- Do we want to collect any other Location data on this form? (ex: county, …
> Community resource addresses

- app/views/contributions/_top_level_card.html.erb
I think our team usage of peer-to-peer is potentionally confusing to community members new to this application. That phrase means different things in different contexts, so I'd like to reduce potential confusion.
I'm open to further changes to this if you'd like to improve the wording
Mobile breakboint:
Wider breakpoint:
n/a
This will hopefully improve legibility of this warning message
This is a wording change that should have no security impact
I suppose we're now leaking a small amount of info about who has or has not entered their contact info. That is certainly a hard think to leverage in isolation, though
> update wording on peer claim of contributions

- app/forms/base_form.rb
- spec/forms/base_form_spec.rb
Discovered a small [bug](https://github.com/AaronLasseigne/active_interaction/issues/499) in `active_interaction` where multi-part date params such as those generated by `date_select` are correctly parsed but not recognized by the `given?` method. We rely on this method to filter params in our form objects -- in order to support partial updates, we filter out any params that were not given, only applying those that were.
> Workaround bug with multipart date in ActiveInteraction::Base#given?

- app/controllers/community_resources_controller.rb
- app/forms/base_form.rb
- app/forms/community_resource_form.rb
- app/models/community_resource.rb
- app/models/community_resource_service_area.rb
- app/policies/community_resource_policy.rb
- app/views/community_resources/_form.html.erb
- spec/forms/base_form_spec.rb
- spec/forms/community_resource_form_spec.rb
- spec/requests/community_resources_spec.rb
Primarily makes location fields optional on the `CommunityResource` form and ensures a 1-1 relationship betweeen CommunityResources and their Locations. Also introduces some new tools and patterns for working with Form objects.
?
> Improve locations on community resources

- doc/structure-of-contribution-filters.md
The filtering code provides us a nice level of flexibility in adding new features. As a tradeoff, it's now harder to understand
Added a markdown document to describe the key parts of the architecture of how we sort and filter contributions for display in the Vue.js code. The description here should be fairly accurate for both the current code base and the proposed changes in https://github.com/rubyforgood/mutual-aid/pull/546
I'd like to finish https://github.com/rubyforgood/mutual-aid/pull/546
Please suggest edits!
Hopefully this makes our code easier to understand
Security concerns are not discussed in this document
- ❌ Tests have been added, or an explanation has been given why the features cannot be tested
- ❌ Entry added to CHANGELOG.md if appropriate
> [skip ci] add initial draft of contribution filtering doc

- app/javascript/components/NavBar.vue
- app/policies/nav_bar_policy.rb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_links.html.erb
- spec/policies/nav_bar_policy_spec.rb
- Make the Sign Up more obvious
- Add button Sign Up next to Log In on the Navbar
- Add button Sign Up right next to Log In button in Login Form
> make Sign Up more obvious

- app/controllers/users_controller.rb
- app/lib/user_role.rb
- app/models/user.rb
- app/policies/user_policy.rb
- app/views/layouts/_navbar.html.erb
- app/views/users/_form.html.erb
- app/views/users/index.html.erb
- app/views/users/show.html.erb
- spec/lib/user_role_spec.rb
- spec/requests/users_spec.rb
Admins need to be able to edit user roles.
Fixes #843 
- Displays user roles in the UI
- Allows only sys_admin and admin roles to edit other users' role
- Fixes a request spec that asserts a user's email can be updated
- Makes rendering of a `logo_url` in the navbar conditional on an existing organization that is the instance owner and actually has a logo_url
See above
A couple of request tests were added but I didn't add any feature tests that would make assertions on what's rendered in the UI. I don't see feature tests used here so far but could add that if that's a direction the project is going.
N/A
I removed the `User#role` getter as it was not used anywhere in the codebase and was block the default Rails getter that would return the user's `role` attribute. Instead an ActiveRecord …
> Displays and allows roles to be editable by admins (sys_admin & admin)

- .circleci/config.yml
- app/controllers/asks_controller.rb
- app/controllers/offers_controller.rb
- app/controllers/public_pages_controller.rb
- app/controllers/submissions_controller.rb
- app/helpers/application_helper.rb
- app/interactions/email_new_submission.rb
- app/interactions/email_peer.rb
- app/interactions/generate_landing_page_json.rb
- app/javascript/components/NavBar.vue
- app/mailers/peer_to_peer_match_mailer.rb
- app/mailers/submission_mailer.rb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/layouts/_navbar.html.erb
- app/views/peer_to_peer_match_mailer/peer_to_peer_email.html.erb
- app/views/shared/_organization_logo.html.erb
- doc/testing.md
- spec/forms/community_resource_form_spec.rb
- spec/interactions/email_new_submission_spec.rb
- spec/interactions/email_peer_spec.rb
- spec/interactions/generate_landing_page_json_spec.rb
- spec/requests/community_resources_spec.rb
- spec/requests/public_pages_spec.rb
Our ruby specs currently depend on the test database being seeded, which is non-standard and surprising, particularly for new contributors.
Relies on existing specs and some manual testing of nav bar, login and signup pages.
Note this is built on top of #926 which renamed `Organization.current_organization` to `.instance_owner`. However the changes here aren't really dependent on that particular change.
> Free specs from seeding

- doc/testing.md
- spec/rails_helper.rb
Happened to notice this in `doc/testing.md`:
> BE SURE to include the line `after { Warden.test_reset! }` after the `before do` block with the `login_as` method within it. This prevents unexpected state data of the user from hanging around and causing errors.
I'm pretty sure none of us are doing that 😅 !
This PR adds an `after` hook to `rails_helper.rb` that automatically resets `warden` for request specs.
> Force Warden.test_reset! after request specs

- app/presenters/announcement_presenter.rb
- app/views/announcements/show.html.erb
- config/locales/en.yml
#885 
- Make the Announcement show page like a card, make it fancy
- Add some Bulma style for Announcement show page
--Without edit permission:
> make Announcement show page like a card

- CHANGELOG.md
- app/controllers/claims_controller.rb
- app/interactions/claim_contribution.rb
- spec/interactions/claim_contribution_spec.rb
Fixes a [bug](https://mutual-aid-app.slack.com/archives/C01LSKPJZNW/p1618666427000700) in peer-to-peer claims.
acd210de08 introduced a bug where `Organization` was added as a required argument to `EmailPeer`, but not
supplied by `ClaimContribution` and `ClaimsController`.
This bug went uncaught because `claim_contribution_spec` was mocking EmailPeer. Changing the spec to let `ClaimContribution` call composite interactions as it normally would surfaces any such integration problems.
?
?
> Fix bug in Claiming introduced in acd210de08

- CHANGELOG.md
- app/policies/person_policy.rb
- spec/policies/person_policy_spec.rb
Discovered a bug while working on #950, extracted the fix here so it can be merged post haste.
`PersonPolicy.own_person` was implemented as `person.user_id == user&.id`.
With a guest user, where user is nil, this works but only if person has a user; if it doesn't, then the two nils match and `own_person` returns true.
This effectively meant any guest user could access any Person record that didn't have an associated user record.
This is actually common because listings can be created by guests, in which case we generate a Person record w/o a user to associate it with.
To recreate, guest users need to guess the record id of a an existing `Person` record with no associated `User`.
?
?
I believe this fixes an existing vulnerability.
> Fix bug in PersonPolicy that allows guest to access other People

- .rubocop.yml
- .rubocop_todo.yml
Building on #935, disables Standard rules around string literals.
Standard requires all string literals to use double-qoutes instead of single-quotes.
This makes sense and is easily auto-corrected _but_ i'm not sure of the value in enforcing this.
The argument that using double-quotes saves time (in trying to guess whether a string will need interpolation in the future, or when that does change) is sound. However, any author who ascribes to this is free to exclusively use double-quotes.
The downside of enforcing the Standard double-quotes is a significant disruption to git history caused by this pervasive auto-correction.
That in itself feels like enough reason to just disable this rule.
Relying on our existing suite to catch any regressions.
?
Really curious the team's thoughts on this.
> Rubocop string literals

- .rubocop.yml
- .rubocop_todo.yml
Building on #935, configures rules related to single-line and empty method definitions
Standard doesn't allow for single-line methods, but i'm proposing here that they can be useful in certain situations. Some of our policy files are good examples.
Moreover, single-line methods don't often coming up as an issue in our codebase or in the wild.
As such, i'm proposing:
* Allow single-line methods
* Allow empty methods, enforcing a `compact`, single-line style
* Allow adjacent single-line methods w/o an empty line between them
Relying on our existing suite to catch any regressions.
?
?
> Rubocop single line methods

- app/controllers/asks_controller.rb
- app/controllers/offers_controller.rb
Sorry for my english.
The navbar is always hidden on `asks/new` and `offers/new` (#806).
The problem is that the navigation bar is still hidden because the option in settings is not used. We need to hide the navbar if the boolean is `false` like in other controllers.
I don't know what to add.
Unknown.
Not seem to be concerned.
Not seem to be concerned.
Not seem to be concerned.
Not seem to be concerned.
I think the reviewer will check this so i let it empty.
> 806 : the navbar is not displayed correctly

- app/models/person.rb
- app/validators/email_validator.rb
- spec/models/person_spec.rb
- spec/validators/email_validator_spec.rb
Sorry for my english.
We need to validate emails in person (#827).
The validator is in the guide about [validations](https://guides.rubyonrails.org/active_record_validations.html#custom-validators).
A test is available now in `person_spec.rb`.
Unknown.
Not seem to be concerned.
Not seem to be concerned.
Not seem to be concerned.
Not seem to be concerned.
I think the reviewer will check this so i let it empty.
> 827 : emails validation in person

- app/javascript/pages/browse/ListBrowser.vue
- app/javascript/pages/browse/TileListItem.vue
Shows contributor's name on the List and Tile views of the Contributions page (already shown on Map view).
https://github.com/rubyforgood/mutual-aid/issues/537
Contributor's name is stored as (Name) along with details of the offer in the name field. I've used a regex to match for text within brackets.
I wasn't totally clear on the requirements - do we want the ability to Toggle showing contributor names as well?
If so, how would we want this to look on the page - would a toggle box belong alongside the Filters given that it's not a Filter but a display option?
> Show contributor name on Contributions page

- .circleci/config.yml
- Gemfile
- Gemfile.lock
- bin/test
- doc/testing.md
- spec/rails_helper.rb
- spec/spec_helper.rb
- spec/system/registration_spec.rb
We've been needing some system-level test coverage for a while now. This PR sets up the minimal groundwork needed to start writing them.
With these changes, our `.circleci/config.yml` is in need of some refactoring; will follow up with a PR to address this.
?
> Lay groundwork for system specs

- lib/tasks/add_user.rake
Previously there has not been an easy way to add a new user to the application prior to configuring a SMTP server to dispatch confirmation emails.
Create a rake task that
Omitted, as this was a very simple change.
Omitted, as this task is only meant to be run by developers in non-production environments
1. Add a simple test to ensure syntactic/semantic comparability over time.
2. Perhaps add a safety check to ensure that developers must manually specify, similar to `DISABLE_DATABASE_ENVIRONMENT_CHECK=1`
Omitted, as this is a developer-only feature.
This script cannot be run without administrator shell access to the server hosting the application, and anyone who has administrator shell access to the server is able to do anything they want. Therefore, security of this script isn't really …
> Adds a simple script to add a single user to the app

- package.json
- yarn.lock
With the previous version, changes to source files weren't being picked up in watch mode (`yarn test -w`).
Simple upgrade. Couldn't find any definitive documentation but it appears the bug was related to a problem with having multiple available versions of the `chokidar` library.
?
> Upgrade mochapack to fix source files not being auto-refreshed

- app/controllers/application_controller.rb
- app/controllers/matches_controller.rb
- app/helpers/application_helper.rb
- app/models/importers/custom_form_question_importer.rb
- app/models/importers/submission_response_importer.rb
- app/models/match.rb
- app/models/submission_response.rb
- app/refinements/to_boolean.rb
- app/views/submissions/_submission_responses.html.erb
- spec/models/submission_response_spec.rb
- spec/refinements/to_boolean_spec.rb
As i was working through rubocop offenses, [`Security/YAML.load`](https://docs.rubocop.org/rubocop/cops_security.html#securityyamlload) surfaced in several places. While the easy fix for this is to use `.safe_load` instead, i was also curious why we were using YAML in the first place.
It appears we are using `YAML.load` as a way to convert a string to a boolean. While this works, i don't find it to be intention revealing. This PR introduces an alternate way to solve this.
I considered three alternative APIs:
1. A utility method such as `Util.to_boolean`. I usaully prefer the explicitness of this approach over modifying ruby objects, but in this instance, `.to_boolean` felt like a natural additional, similar to other casting methods such as `.to_i`, `to_f` etc.
2. Monkey-patch, which would …
> Introduce ToBoolean refinement to replace YAML.load

- app/helpers/application_helper.rb
- app/presenters/announcement_presenter.rb
- app/presenters/base_presenter.rb
- app/views/announcements/show.html.erb
- spec/helpers/application_helper_spec.rb
Extracts some small improvements to our presenter code out of #950 
?
> Presenter improvements

- app/models/listing.rb
- app/views/claims/new.html.erb
- app/views/contributions/_top_level_card.html.erb
- spec/models/listing_spec.rb
Hi! I'm new here. This is my PR to modify the button text for Asks: https://github.com/rubyforgood/mutual-aid/issues/871
I've changed the button copy for claiming listings. When it's an ask, copy is `Help this person` (proposed change in https://github.com/rubyforgood/mutual-aid/issues/871) and when it's an offer `Claim this offer` (no change from previous version). 
Because both `Offer` and `Ask` inherit from `Listing`, I've created a method `Listing#claim_button_text` that can be called by both types and returns the correct button copy. 
This is a pretty minor UI change but I've written a spec that covers both cases. 
N/A
N/A 
This change doesn't affect or worsen the existing accessibility.
I don't think this change has any security implications. 
N/A
> Change button text on Claim page for Ask

- app/policies/nav_bar_policy.rb
- spec/policies/nav_bar_policy_spec.rb
To fix #992, show the `Feedback` NavBar button only to Admins & Sys-Admins
I chose those approach after seeing that the route triggered by the `Feedback` button uses the `SoftwareFeedbacksController` is derived from `AdminController`, which allows actions only by users with either the `admin` or `sys_admin` role. That is, I inferred the UI was incorrectly offering the button.
Change `NavBarPolicy#visible_buttons` to include `Feedback` only for `User`s with either the `admin` or `sys_admin`.
Moved adding `Feedback` to the allow-list from the line with `NavBarPolicy#visible_buttons`'s simple non-`nil` check to the line guarded with the call to `ApplicationPolicy#can_admin?`
The PR modifies existing examples, removing the expectation for `Feedback`'s presence for `neighbor` cases.
More about …
> Make NavBarPolicy allow Feedback only for Admins

- Procfile.dev
- doc/setup.md
Simplify local development by defining the processes involved in a new `Procfile.dev`. This file is compatible with several process managers such as [foreman](https://github.com/ddollar/foreman), [invoker](https://invoker.codemancers.com/) and [node-foreman](https://github.com/strongloop/node-foreman).
1. I looked into the possibility of using the existing `Procfile` for both production and development. This would've required adding intelligence to startup scripts such as `bin/webpack-dev-server` so that they would no-op in production. Turned out to be more complicated because `foreman` interprets any early process exit as an error and aborts all processes.
1. I chose not to introduce a convenience script such as `bin/serve` for a few reasons:
1. I didn't want to assume/prescribe a …
> Add Procfile.dev and instructions for its use.

- CHANGELOG.md
- package.json
Ran into the following issue with node v17:
https://github.com/webpack/webpack/issues/14532
There are other workarounds but i figure this is safer for now, at least until we are able to #906.
> Constrain supported node engines

- app/javascript/components/forms/ContactFields.vue
- app/javascript/components/forms/CustomQuestions.vue
- app/javascript/components/forms/LocationFields.vue
- app/javascript/pages/Ask.vue
- app/javascript/pages/Offer.vue
- app/javascript/utils/form.js
- spec/javascript/utils/form.spec.js
Enhances `fieldNameWithPrefix` utility function so it can support multiple segments in the field name.
Mostly wanted to rescue this useful change from a wip branch that probably won't get merged in.
Renames the function as `composeFieldName` and makes the implementation recursive.
In combination with the `partial` function, allows components to generate field names for deeply nested attributes.
Enhanced existing unit test.
> Compose field name
