CONTRIBUTING.md
LICENSE.md
ORIENTATION.md
README.md
code-of-conduct.md

Looking for feedback here! Did a cursory first pass just to get these up and running.

Starter docs

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/custom-spacing.scss
app/javascript/components/AboutSection.vue
app/javascript/components/Orientation.vue
app/javascript/components/index.js
app/javascript/entry_points/index.js
app/javascript/entry_points/orientation.js
app/views/devise/registrations/edit.html.erb
app/views/devise/sessions/new.html.erb
app/views/external_resources/_form.html.erb
app/views/external_resources/index.html.erb
app/views/external_resources/new.html.erb
app/views/landing_page/show.html.erb
app/views/layouts/_notices_and_alerts.html.erb
app/views/layouts/application.html.erb
app/views/listings/_form.html.erb
app/views/listings/index.html.erb
app/views/listings/new.html.erb
package-lock.json
package.json
yarn.lock

Current implementation still requires login. Landing page now uses Vue. CSS and forms have been un-broken.

Frontend orientation

---

app/assets/stylesheets/application.scss
config/initializers/simple_form.rb
config/initializers/simple_form_bulma.rb

This *works* (TM), but needs to be further reviewed for use of bootstrap classes.
I lifted it from another project that used bootstrap and took a first pass on bulma classes.
I'm sure there's some cruft in here, but I can't find it and it works as is and I think is gtg?

Add intiial config for simple_form. Needs more review to further bulma-ify-it.

---

.prettierrc.yml

Definitely open to discussion on any of these settings and am not tied to any of them.
Does _not_ integrate any automated checking or fixing for now. Wanted to give us time to agree on conventions and try them out before enforcing them in any automated way. Also allows us to backburner this PR.
See https://prettier.io/docs/en/editors.html for ways to integrate into editors.

Add prettier config

---

app/views/announcements/index.html.erb

Needed an `&.` on Announcement index (so truncate isn't called on nil)

Add conditional on display index for when description is nil

---

.circleci/config.yml
.env.test

This should resolve the problems with #95 and other PRs that were failing

Change Circle CI config so changes to .env files matter less

---

app/views/devise/mailer/_reset_password_instructions.html.erb
app/views/devise/mailer/password_change.html.erb
app/views/devise/mailer/reset_password_instructions.html.erb
app/views/devise/mailer/unlock_instructions.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
config/initializers/devise.rb

Makes changes to template text, and draws from new env vars, as well as some changes to the devise initializer.

Update devise integration

---

app/views/admin/landing_page.html.erb

* Add all models to admin_landing page
* Split the list into Data and Settings

Update admin landing page

---

app/controllers/users_controller.rb
app/helpers/application_helper.rb
app/models/communication_log.rb
app/models/listing.rb
app/models/match.rb
app/models/offer.rb
app/models/person.rb
app/views/people/_profile_listings_section.html.erb
app/views/people/index.html.erb
app/views/people/show.html.erb
app/views/users/_form.html.erb
app/views/users/index.html.erb
app/views/users/show.html.erb

This provides links and buttons between User Account and Person Profile, and is a start at Person Profile design (required some assn renaming and temporary model methods).
Would love to refactor next week -- with help!

Profile page workflow and starter design

---

app/views/layouts/_view_header.html.erb

Small changes to view_header:
- Swap order of params[:controller_name] and controller_name
- Add new to the conditional that decides whether or not to display the form
TODO rename view_header
- this prob shouldn't be called view_header anymore since it also decides which body partial to display

Give priority to controller_name params and include new in form display conditional

---

app/assets/stylesheets/bulma_simple_form_customization.scss

- Add classes to simple_form_bulma_customization to improve display of radio buttons

Add more spacing for radio buttons

---

app/views/admin/_admin_buttons_list.html.erb
app/views/admin/landing_page.html.erb
app/views/admin/volunteer_admin.html.erb

- Refactor/DRY up admin landing_page button code
- Added option to include(or not) system_settings button as one of the button rows

Refactor admin landing_page button code

---

app/controllers/people_controller.rb
app/models/person.rb
app/views/layouts/_view_header.html.erb
app/views/people/_form.html.erb

- Add constants to person.rb to have fixed list of preferred_contact_method values
- Add those values to form dropdowns
- DRY controller and add dropdown values to multiple actions
- Update validation to handle non-"phone" values to check if the phone field is populated

Better handle phone contact preference types

---

app/controllers/application_controller.rb
app/views/admin/_admin_buttons_list.html.erb
app/views/admin/landing_page.html.erb
app/views/admin/volunteer_admin.html.erb

Some random changes
- DRY admin pages, update admin links (w params yet to be implemented)
- set_system_setting in ApplicationController

[ON HOLD] Some randoms

---

app/models/ask.rb
app/models/donation.rb
app/models/match.rb
app/models/offer.rb
app/models/person.rb
app/views/people/show.html.erb

...(and a merge fix)
Fixes to Profile page (person#show )
- Add donations assn to person.rb
- Change match queries to drill down in to the correct tables (remove SQL table name ambiguity)
- Remove titles for Edit and Account buttons

More data revealed issues w queries on Profile page, so here are fixes

---

app/javascript/components/AuthTokenInput.vue
app/javascript/components/DeleteButton.vue
app/javascript/components/NavBar.vue

Tiny PR extracting an `AuthTokenInput` component.

Extract AuthTokenInput for reuse on any form

---

app/javascript/components/NavBar.vue

Co-authored-by: maebeale <maebeale@gmail.com>

added Home link to the Vue navbar

---

app/controllers/public_controller.rb

- We'd decided to do this to stay Railsy
- I was prompted to complete this bc I wanted the PublicController to have access to @system_setting and the :locale param, which are set in ApplicationController

Refactor PublicController to inherit from ApplicationController

---

app/models/user.rb

- Hard-coded to true for now
- Def need a review of Pundit options soon
- This permission is one above admin for users
who will be able to configure the system. (Very open to renaming!)

Add sys_admin permission to user.rb

---

app/views/mobility_string_translations/_form.html.erb

- Don't try to access the key for /new
- NOTE: this model is going to get wiped out to defer to Mobility's model
- NOTE: this UI will be replaced by editing things on their respective Edit pages

Fix conditional display of translation key

---

app/javascript/pages/Orientation.vue

- Try 2-column layout for text and buttons
- Streamlined desired actions to one button per section
- Adding 'Both' section for now (this is discussion point)

Change welcome/landing_page orientation

---

.vscode/launch.json
app/controllers/listings_controller.rb
app/javascript/entry_points/browse.js
app/javascript/pages/Browse.vue
app/javascript/pages/browse/ContributionFetcher.js
app/javascript/pages/browse/Filters.vue
app/views/listings/index.html.erb
lib/filterCategories.json
lib/filters.json
package.json
spec/javascript/pages/Browse.spec.js
spec/javascript/pages/browse/ContributionFetcher.spec.js
spec/javascript/pages/browse/Filters.spec.js
yarn.lock

Add basic filtering functionality
- UI: have the category and urgency tags always be two rows on tablet to solve the problems with intermittent wrapping due to variable tag list length
- UI: Improve the visual indicators on the filter category expand/collapse accordion
- UI/functionality: allow a category checkbox that toggles all of the subcategories (to select all urgency levels simultaneously, for example)
- Add categories that should be checked by default (can be fed from the Rails side)

Basic filtering UI

---

app/controllers/application_controller.rb
app/controllers/people_controller.rb
app/controllers/service_areas_controller.rb
app/models/user.rb
app/views/layouts/_view_header.html.erb
app/views/people/_form.html.erb
config/locales/en.yml

- Add preferred_locale to user so it can be detected if person
- Change person preferred_locale to default to preference or system_locale
- Set @system_locale for reference throughout app
- Change view_header to use locale yml for klass.model_name.human
- Add some en.yml content

Locale nuances

---

app/models/ask.rb
app/models/listing.rb
app/models/offer.rb

- Adjust `def name` in Listing and remove it from Ask and Offer
- This might affect serializers, so need to check that out
- Def don't want Ask or Offer names to only be tag list

Change listing names

---

app/controllers/donations_controller.rb
app/models/donation.rb
app/views/donations/_form.html.erb
app/views/donations/_person_fields.html.erb
app/views/donations/show.html.erb

- Accept nested attributes for Person
- Improve UI of field on views

Refine donations

---

app/controllers/community_resources_controller.rb
app/models/community_resource.rb
app/views/community_resources/_form.html.erb
app/views/community_resources/_organization_fields.html.erb
app/views/community_resources/index.html.erb
app/views/public/community_resources.html.erb

- Remove json blocks from controller
- Build an Organization and accept nested_attributes
- Change layout
- Change decorator methods

CommunityResources refinement

---

app/controllers/asks_controller.rb
app/controllers/community_resources_controller.rb
app/controllers/matches_controller.rb
app/controllers/offers_controller.rb
app/controllers/public_controller.rb
app/controllers/public_pages_controller.rb
config/routes.rb

- Move them to PublicPagesController, which inherits from PublicController
- Change Asks and Offers Controllers to inherit from PublicController
- Change Matches to route to contributions_public_path after completion
- Adjust routes (and change indentation)

Remove actions from Public

---

db/migrate/20200511014005_remove_constraint_on_translated_models.rb
db/schema.rb

- Mobility leaves translated field empty (e.g. name on CommunictyResource)
- The db had constraints and there are model constraints
- Def need a working plan for validations/constraints in Mobilityland

Handle translation nulls

---

app/models/importers/base_importer.rb

Add base importer class so future importers can be written quickly.
This class handles errors, adds logging statements, etc
Happy to tweak as needed!

Add base importer

---

app/models/importers/custom_form_question_importer.rb
db/dev_seeds/custom_form_questions_LAMA.csv
db/dev_seeds/seeds_dev.rb
db/dev_seeds/seeds_lama.rb

- checking this csv in so it is a sample for future groups to use
- move seeds_dev into this folder
- add custom_form_question_importer building off base_importer and history_log

Add LAMA seeds for custom_form_questions

---

app/models/announcement.rb
app/models/community_resource.rb

Add scopes for landing page stats

---

app/javascript/pages/Orientation.vue

The b-buttons weren't active links on Orientation.vue
- I tried a bunch of different incantations remote-link, adding a new component, etc, and couldn't get any of the Vue-link things to work.
- Replaced them w a href's for now just so they go somewhere
- Still could adjust WHERE the go, and we prob want to revert to b-button syntax later

Make orientation buttons links

---

app/blueprints/person_blueprint.rb
app/blueprints/service_area_blueprint.rb
app/interactors/save_listing.rb
app/interactors/save_person.rb
app/javascript/pages/Offer.vue
app/javascript/pages/offer/CategoryFields.vue
app/javascript/pages/offer/ContactFields.vue
app/javascript/pages/offer/LocationFields.vue
app/models/organization.rb
app/views/offers/new.html.erb

* Add form preamble and footer in `/offers/new.html.erb`
* Note: this introduces some whitespace changes; diff is probably better viewed with `?w=1`
* Make field labels a bit more prominent with `is-medium`
* Add `message`s to a couple of field fields, such as name
* Give categories a label and some instructional text
* Add skills and notes fields
* Fixes bug with `preferred_contact_method` not being retained.

Offer form bugfixes and changes to get it closer to LAMAs form

---

app/views/communication_logs/index.html.erb
app/views/communication_logs/show.html.erb

Change index edit_button to show_button
Change Edit text on bottom of form to edit_button

Update communication_logs buttons

---

app/controllers/offers_controller.rb
app/javascript/components/forms/CategoryFields.vue
app/javascript/components/forms/CommentsField.vue
app/javascript/components/forms/SubmitButton.vue
app/javascript/components/forms/index.js
app/javascript/entry_points/ask.js
app/javascript/entry_points/index.js
app/javascript/pages/Ask.vue
app/javascript/pages/Offer.vue
app/views/asks/new.html.erb
config/routes.rb

Minimal, functional `/asks/new` 🐇 .
Missing some questions when compared to the LAMA [request form](https://docs.google.com/forms/d/10XnUMY4wwp4o2v0UmOQdQ6XcogjkSMtzlp-iXI65v6s/edit):
* "Do you wish to be contacted about donations..."
* "Does your request need to remain anonymous?"
* "Number of people in the household"
* "Is a member in your household over the age of 50?"
* Recurrence and Urgency, which we're planning to attach to categories.

Request support

---

db/schema.rb

Correcting for prior PR omissions re schema changes...
- Set boolean defaults and indexes
- Add submission_id and FK to listing
- Update location_id to be null:false and an FK on service_areas

Schema updates

---

app/controllers/listings_controller.rb
app/controllers/submissions_controller.rb
app/models/listing.rb
app/models/submission.rb
app/views/listings/_form.html.erb
app/views/submissions/_form.html.erb
app/views/submissions/index.html.erb
app/views/submissions/show.html.erb
db/migrate/20200513015136_add_submission_to_listing.rb

- Connect submission to listing (submission has_many :listings)
- Update views
- Display json of submission.body (storage of listings on create -- tbd)

Add submission to listing

---

app/controllers/asks_controller.rb

- Since it's no longer inheriting from ListingsController, we don't get it from super

Adding update action to AsksController

---

app/controllers/users_controller.rb
app/models/user.rb
app/views/users/_form.html.erb
app/views/users/_person_fields.html.erb
app/views/users/edit.html.erb
app/views/users/show.html.erb

- Add nested person vars to User
- Comment out extra button for now (was erroring)
- Change person fields to f.input vs f.association (not supported for fields_for)
- Update view header titles
- Change User Show to only show user fields

Add nested person to user

---

config/environments/development.rb

Not sure when this got removed...

Add localhost back

---

app/controllers/custom_form_questions_controller.rb
app/models/importers/custom_form_question_importer.rb
app/views/custom_form_questions/_form.html.erb
db/dev_seeds/custom_form_questions_LAMA.csv
db/migrate/20200514102503_add_form_hook_to_custom_form_question.rb
db/schema.rb

- Add form_hook to CustomFormQuestion in prep for making Forms iterate over CustomFormQuestions
- Added field to importer, tho the seed data isn't populated yet

Add form_hook to CustomFormQuestion

---

app/blueprints/contribution_blueprint.rb
app/controllers/contact_methods_controller.rb
app/models/contact_method.rb
app/models/person.rb
app/views/contact_methods/_form.html.erb
app/views/contact_methods/index.html.erb
app/views/people/index.html.erb
db/migrate/20200514101411_add_icon_to_contact_method.rb
db/schema.rb
db/seeds.rb
spec/blueprints/contribution_blueprint_spec.rb

- Add `icon_class` to `contact_method` so that can be edited at admin level
- Display on Person index
- Add icon classes to seeds
- Some editor adjustment of whitespace
TODO: add it to blueprint so Vue doesn't store which icons are for what

Add icon to contact method

---

app/models/mobility_text_translation.rb

- We will prob want to figure out how to use the mobility classes
- Adding this for now
- It gets called by truncate_tables to remove this data via rake task

Add mobility_text_translation model

---

app/models/ask.rb
app/models/listing.rb
app/models/offer.rb
app/views/listings/listings_index.html.erb
app/views/submissions/show.html.erb

- implement `icon_class` method in Listing, Ask, and Offer
- change Listings index to display icon of type
- add icon to View Listing button on Submission show

Ask, Offer, and Listing all know which icon_class to display

---

app/views/admin/landing_page.html.erb

- they were both rendering percentage total based on asks
- move fraction text to end of key rather than middle

Change pie colors on admin landing (and rearrange key)

---

CONTRIBUTING.md
LICENSE.md
ORIENTATION.md
README.md

- Refactor README
- Remove references to Heroku CLI/Procfile since we're not using it
- Add more info re testing
- Try to clarify and split out deployment from Heroku/Docker/local setup stuff
- Update ORIENTATION with some additional detail
- Change license and code of conduct to reflect current Ruby for Good relationship (tentative)

Docs updates

---

app/controllers/contributions_controller.rb
app/views/contributions/respond.html.erb
app/views/contributions/submission_thank_you.html.erb

- add more buttons/detail to `respond` and `submission_thank_you` pages
- make both publicly accessible (skip user auth)
TODO: respond shouldn't be entirely publicly accessible -- will depend on @system_settings.exchange_type

Update contributions pages

---

app/models/importers/base_importer.rb
app/models/importers/custom_form_question_importer.rb
app/models/importers/submission_response_importer.rb
app/models/importers/user_importer.rb

- enable all the stats/counts called by base_importer
- add begin/rescue for when klass_name can't be converted into a constantized klass
- small display tweaks to custom_form_question importer
- change submission_response importer to detect delivery_method
- add basic user importer

Tweak existing importers and add a new one for users

---

app/views/listings/_form.html.erb

Add is-grouped div to listings form

Add grouping to listings form

---

app/controllers/organizations_controller.rb
app/controllers/positions_controller.rb
app/controllers/teams_controller.rb
app/models/organization.rb
app/models/position.rb
app/models/team.rb
app/views/admin/landing_page.html.erb
app/views/organizations/_form.html.erb
app/views/organizations/org_chart.html.erb
app/views/positions/_form.html.erb
app/views/teams/_form.html.erb
config/routes.rb
db/migrate/20200515031229_add_standing_meeting_schedule_to_team.rb
db/migrate/20200515035041_display_on_org_chart.rb
db/schema.rb

- Add display_on_org_chart methods to Organization, Team, and Position
- Update in MVC (including scopes on model) 
TODO - move that crazy css file to asset pipeline

Add org chart

---

app/views/contact_methods/index.html.erb

add yes_no wrapper around enabled boolean

Update contact methods index decorator

---

app/controllers/donations_controller.rb
app/controllers/people_controller.rb
app/controllers/users_controller.rb
app/models/communication_log.rb
app/models/contact_method.rb
app/models/importers/submission_response_importer.rb
app/views/communication_logs/_form.html.erb
app/views/contact_methods/show.html.erb
app/views/donations/_person_fields.html.erb
app/views/users/_person_fields.html.erb
db/seeds.rb
db/seeds/dev_seeds.rb
lib/tasks/db.rake

- Add some fields
- Set autoemail ContactMethod to enabled: false so no one can choose it in the dropdowns
- Fix typo

Setup seeds

---

app/controllers/announcements_controller.rb
app/controllers/categories_controller.rb
app/controllers/communication_logs_controller.rb
app/controllers/contact_methods_controller.rb
app/controllers/custom_form_questions_controller.rb
app/controllers/donations_controller.rb
app/controllers/listings_controller.rb
app/controllers/locations_controller.rb
app/controllers/matches_controller.rb
app/controllers/mobility_string_translations_controller.rb
app/controllers/organizations_controller.rb
app/controllers/people_controller.rb
app/controllers/positions_controller.rb
app/controllers/service_areas_controller.rb
app/controllers/shared_accounts_controller.rb
app/controllers/submission_responses_controller.rb
app/controllers/submissions_controller.rb
app/controllers/system_locales_controller.rb
app/controllers/system_settings_controller.rb
app/controllers/users_controller.rb

- remove extra respond_to blocks
- add some set_form_dropdowns
- alphabetize some strong params

Controller cleanup

---

app/javascript/components/NavBar.vue
app/javascript/components/forms/FeedbackButton.vue
app/javascript/components/forms/index.js
app/views/software_feedbacks/_form.html.erb

- Add button component to navbar
TODO: somehow get it to put `window.location.href` into `page_url=`

Add feedback button to nav (that captures href)

---

app/blueprints/category_blueprint.rb
app/javascript/components/forms/CategoryFields.vue
spec/javascript/components/forms/CategoryFields.spec.js

Also show category/subcategory descriptions when selected.

Add subcategories to Ask/Offer form

---

app/controllers/communication_logs_controller.rb
app/controllers/matches_controller.rb
app/controllers/people_controller.rb
app/helpers/application_helper.rb
app/helpers/communication_log_buttons.rb
app/helpers/index_action_buttons.rb
app/models/communication_log.rb
app/models/listing.rb
app/models/match.rb
app/models/person.rb
app/models/submission.rb
app/views/admin/landing_page.html.erb
app/views/communication_logs/_form.html.erb
app/views/communication_logs/show.html.erb
app/views/layouts/_view_footer_buttons.html.erb
app/views/matches/_communication_history.html.erb
app/views/matches/_communication_log_quick_buttons.html.erb
app/views/matches/_form.html.erb
app/views/matches/_recipient_and_provider.html.erb
app/views/matches/_search_boxes.html.erb
app/views/matches/edit.html.erb
app/views/matches/index.html.erb
app/views/matches/new.html.erb
app/views/matches/show.html.erb
app/views/people/profile_partials/_profile_listings_section.html.erb
app/views/people/show.html.erb
app/views/submissions/_form.html.erb
config/initializers/simple_form_bulma.rb
config/routes.rb
db/seeds/dev_seeds.rb

This provides an initial, rudimentary workflow for Matching.
- Start at Contributions page
- Go to matches/new (but only select the Provider and Receiver)
- Adjust matches & log communications
- Save
- Lots of small design changes to display names, and buttons/params between things

Matching workflow adjustments [temporary code]

---

app/controllers/communication_logs_controller.rb
app/javascript/components/NavBar.vue
app/javascript/pages/Orientation.vue
app/javascript/pages/browse/ListBrowser.vue
app/javascript/pages/browse/TileListItem.vue
app/views/communication_logs/_form.html.erb
app/views/public/announcements.html.erb
app/views/public/community_resources.html.erb

- Change [ADMIN/P2P] -> [*] so it's less obtrusive
- Add Matches link to navbar
- Change order/importance/coloring of Respond vs Match buttons on Contributions page 
TODO - couldn't figure out how to make the reply button look nice with text, so made that Respond button text-only for now

Change vue links and text

---

app/models/ask.rb
app/models/offer.rb

Swapped the icon_class out between Ask and Offer

Update listing icon classes

---

app/controllers/users_controller.rb
app/models/user.rb
app/views/devise/confirmations/new.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/users/_form.html.erb
app/views/users/_person_fields.html.erb

- Bulma-ify devise views
- Add buttons to User form
- Move person select to end of nested partial
- If @user == current_user, redirect to /user/edit
- Change user name to be person&.name || email

Update devise workflows

---

app/controllers/listings_controller.rb
app/models/contribution.rb
app/models/listing.rb
app/views/contributions/respond.html.erb
app/views/listings/listings_index.html.erb
app/views/matches/_communication_history.html.erb
app/views/submissions/index.html.erb
db/seeds/dev_seeds.rb

- Add TYPES constant to contribution.rb (and iterate over it to display sections)
- Add ask? and offer? methods to listing.rb (and use them to conditionally display)
- Add text when there are no items in section

Refactor and improve view code

---

app/models/ask.rb
app/models/offer.rb

Remove unnecessary icon_class methods from Ask and Offer

Remove methods re icon_class, bc defined in listing.rb

---

app/controllers/communication_logs_controller.rb
app/views/communication_logs/index.html.erb

Use auto_generated field to conditionally display edit/show button on index

Dynamically show different buttons on communication_logs index

---

app/views/communication_logs/show.html.erb

Add index button to communication_logs/show

Add index button to communication_logs show

---

app/views/feedbacks/_form.html.erb

Change feedback rating to 1-5 (started at 1-10, but that's not as easy/stats-friendly as 1-5)

Change feedback rating scale to 1..5

---

db/seeds.rb

Change system_setting.exchange_type default to "fully_moderated" in seeds.rb

change default exchange type to fully moderated

---

app/views/users/_person_fields.html.erb

Nested assn partial (still working up to using it) was calling assn methods instead of fk methods

Change nested assn partial to use id's instead of assn methods

---

app/views/people/profile_partials/_profile_listings_section.html.erb

Change Profile (person/show) to remove tags iteration and instead display asks and offers as buttons (to match style in rest of app)

Use shorthand_display for listing names and remove 'tags' display on profile

---

app/controllers/matches_controller.rb
app/models/match.rb
db/seeds/dev_seeds.rb

- Change names to be more human
- Display human-readable titles on dropdowns

Improve Match status UI

---

db/seeds/dev_seeds.rb

Add default Person and connect to first User (for demo purposes)

Add default person to first user

---

app/controllers/matches_controller.rb
app/views/matches/_form.html.erb
app/views/matches/edit.html.erb
config/initializers/simple_form_bulma.rb
db/migrate/20200526195031_add_exchange_time_to_match.rb
db/schema.rb

LAMA needs to "schedule" matches for pickup at a specific time
- Add field to db
- Add exchanged_at to forms
- Update bulma to show hints above horizontal multiselects (too much padding when below)
- Add link to fill out time until we have a datepicker

Add exchanged_at to Match new & edit

---

app/views/matches/_communication_log_quick_buttons.html.erb
app/views/matches/_search_boxes.html.erb
app/views/matches/index.html.erb

- Add spaces & comma to prompt on Match edit
- Change order of filters on Match index
- Add (hover) titles, titleizing, and upcase to Match index fields for improved readability

Small usability(text/ordering) changes

---

app/controllers/matches_controller.rb
app/views/matches/edit.html.erb

Change `Save and edit match connections` button -> `Edit who this match connects`

Change link text on match to make functionality clearer

---

app/models/listing.rb

Swap order of icon classes. Have already done this a couple times. lol.

Fix icon_class icons! Again.

---

app/views/matches/_contribution_data.html.erb
app/views/matches/edit.html.erb

Change Match Edit
- dry up calls to display contribution data by adding a partial
- change header to match format of other pages

Dry matches edit code with partial

---

db/seeds/dev_seeds.rb

- Add dynamic created_at
- Change the way update_status runs, bc we're not using completed or tentative in the UI rn
- (Leaving these fields alone for now, bc still testing how UI variations)

Rework match (dev) seeds

---

app/views/matches/index.html.erb

Add exchanged_at column to Matches index

Add exchanged_at to matches index

---

db/db_diagram_yEd.graphml

- Realized I hadn't committed this in a while

Update db diagram to latest

---

app/models/importers/base_importer.rb
app/models/shift.rb
app/views/people/show.html.erb
config/application.rb
spec/factories/users.rb

- Change Date.today -> Time.zone.today
- Add timezone default to UTC in config

Correct datetime calls

---

app/views/submissions/index.html.erb

DRY up code on Submissions index to determine type

Use model method to determine type instead of extra var declaration

---

app/views/devise/sessions/new.html.erb

Pull logo_url from model rather than @current_organization instance var

Get current_organization from model to correctly show logo

---

app/helpers/application_helper.rb
app/models/match.rb
app/views/contributions/respond.html.erb

- Move Match data for the Listing to left (and hide "Add tentative Match button" if Match exists)
- Change edit_button text
- Add icon to match.rb for those buttons

Change Respond page display

---

app/controllers/matches_controller.rb
app/views/admin/dispatch_steps.html.erb
app/views/admin/landing_page.html.erb

- Reorder comments/vars in MatchesController
- Change text and add link to Dispatch Steps page
- Change text for CommunityResources and Announcements

Small text and comment tweaks

---

app/controllers/listings_controller.rb
app/models/listing.rb
app/views/listings/_search_boxes.html.erb
app/views/listings/index.html.erb

- Change comment to update
- Add location_id and service_area_name filters to listings index

Add filters/fields to listings index

---

app/controllers/announcements_controller.rb
app/controllers/asks_controller.rb
app/controllers/community_resources_controller.rb
app/controllers/contributions_controller.rb
app/controllers/offers_controller.rb
app/controllers/public_pages_controller.rb
app/views/layouts/_head.html.erb
app/views/layouts/_main.html.erb
app/views/layouts/_navbar.html.erb
app/views/layouts/_without_navbar.html.erb
app/views/layouts/application.html.erb
app/views/layouts/without_navbar.html.erb

- hide_navbar for forms, public_controller indexes, and form submission thank_you page
- show "Return to admin" if user signed in

Hide navbar on forms, public_controller indexes, and thank you

---

db/db_diagram_yEd.graphml

- includes form-customization-related tables

Latest ERD

---

app/views/people/index.html.erb

Table was going too wide. 
Commenting out for now.

Hide skills on people index

---

app/controllers/matches_controller.rb
app/helpers/application_helper.rb
app/models/listing.rb
app/models/match.rb
app/views/community_resources/show.html.erb
app/views/listings/index.html.erb
app/views/matches/index.html.erb

Improve usability Listings index
- Add match_ids scope and apply to instance var
- Allow triage button to accept button_css_class var
- Add Category and change Match Status to link to Match/Matches, if the… …
- Change triage button text
- Add helper to display UrgencyLevel text w html/css
- Needed class_name designation since UrgencyLevel isn't db backed (yet)
- Change category display to match Contributions (in a few places)
- Rearrange columns on Listings index

Update listings index

---

CHANGELOG.md
app/controllers/asks_controller.rb
app/controllers/offers_controller.rb
app/views/asks/new.html.erb
app/views/offers/new.html.erb
db/seeds.rb

Connect `/asks/new` and `/offers/new` to `Form` model `header_html` and `footer_html`.
---

Customize header/footer text on ask, offer forms

---

app/javascript/pages/browse/ListBrowser.vue
app/javascript/pages/browse/TileListItem.vue
app/models/browse_filter.rb

Remove Match and Profile buttons from Contributions page (on both list and tile views)

Remove profile and match buttons from vue

---

db/seeds.rb

Ensure Form seeds are idempotent

---

app/controllers/public_pages_controller.rb
app/javascript/pages/orientation/AboutSection.vue
app/models/html_sanitizer.rb
app/views/contributions/thank_you.html.erb
app/views/public/about.html.erb
app/views/public/landing_page.html.erb
app/views/system_settings/_form.html.erb

- Created a new class to handle sanitized tags and attributes
- We might want to change the sanitize method later
- We considered sanitize gem, but had issues using it w Ruby 2.7

Add HTML sanitizer to fields we want to accept HTML

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/categories.scss
app/views/categories/index.html.erb

- Remove extra scss file and custom class
- Add bulma classes to style the subcategory rows on Categories index

Replace custom css w bulma classes on categories index

---

app/models/contact_method.rb
app/models/custom_form_question.rb
app/models/importers/submission_response_importer.rb
app/models/service_area.rb

This is still missing the ability to add match data from the MAT Google Form

Extend submission importer to support MAT-style offers and asks

---

app/models/importers/submission_response_importer.rb

- Move question names to bottom of file
- Don't downcase question names
- Search on question NAME, not the object
- Move title to after first_or_create

fix-question-answer-imports

---

app/controllers/people_controller.rb
app/views/people/_form.html.erb
app/views/people/_location_fields.html.erb

- Users weren't able to view/edit address data for People bc it's stored in Locations table

Add nested location data to Person form

---

CHANGELOG.md
app/views/shared/_organization_logo.html.erb

@current_organization wasn't defined, so the login logo was defaulting to the stock image

Get logo_url from current_organization

---

app/blueprints/category_blueprint.rb
app/blueprints/configuration_blueprint.rb
app/models/category.rb

Use visible scope instead of additional association in CategoryBlueprint

---

CHANGELOG.md
app/blueprints/contribution_blueprint.rb
app/javascript/components/MappedIconList.vue
app/javascript/pages/browse/ListBrowser.vue
app/javascript/pages/browse/TileListItem.vue
app/views/contributions/respond.html.erb
app/views/matches/index.html.erb
spec/blueprints/contribution_blueprint_spec.rb

- Add hourglass icon to indicate when a Contribution is inexhaustible

Display inexhaustible icon on Contributions, Matches, Respond

---

CHANGELOG.md
app/controllers/contributions_controller.rb
app/views/admin/landing_page.html.erb
app/views/listings/index.html.erb

- Fix bug where inexhaustible wasn't updating when edited on Triage page
- Update Listings index layout

Inexhaustible edit

---

CHANGELOG.md
app/views/admin/glossary.html.erb

Add more terms to glossary, per stakeholder request

---

CHANGELOG.md

Add Listings index to admin page under Contribution data

---

docker/production/app/Dockerfile

Don't want to be able to update the lockfile while deploying to production!

Install yarn packages with frozen lockfile

---

CHANGELOG.md
app/forms/submission_form.rb
spec/forms/submission_form_spec.rb

Allow for no custom questions on ask/offer form

---

CONTRIBUTING.md
README.md
ansible/appserver.yml

I think I've caught them all. Please let me know if I've missed any

Update git repo links to point to the new Ruby for Good location

---

DEPLOYMENT.md
ORIENTATION.md
README.md
SETUP.md

- Added more reference and text re what mutual aid networks are
- DEPLOYMENT and SETUP seemed to be missing on this merge, so adding back
- Added footer links back to README from the docs
- Linked out to our ORIENTATION doc we'd written a while ago
Co-authored-by: gingeralbertson <gingeralbertson@gmail.com>

More refinement and details added to README including links, etc

---

SETUP.md

Also restructures SETUP.md a bit.
H/T @Gabby (what's your GH handle!?) for finding and working through this gap in our docs!

Add missing instructions for setting up PostgreSQL on Linux

---

CHANGELOG.md
app/mailers/application_mailer.rb
app/mailers/submission_mailer.rb
config/initializers/devise.rb

We were getting a SendGrid error when using SignUp bc the emails weren't sending, prompting us to clean up ENV vars.

Fix devise emails

---

SETUP.md
app/assets/stylesheets/bulma_simple_form_customization.scss
config/initializers/simple_form_bulma.rb

Fixes issue #615 
Have clipped the list and rendered with a scroll, to prevent the form from being overly long. Can adjust if something else is preferred.

615 vertical tag list

---

README.md
doc/contributing.md
doc/deployment.md
doc/orientation.md
doc/seeding.md
doc/setup.md
doc/testing.md

Having too many files in the root of the project can be overwhelming.
Also feels like they belong in `docs/` 😏 .

Move our various docs into the `docs/` directory

---

app/javascript/pages/browse/MapBrowser.vue

FIXME now uses correct comment syntax and doesn't break map

Fix FIXME comment breaking map

---

app/controllers/contributions_controller.rb
app/controllers/public_pages_controller.rb
app/javascript/pages/orientation/Carousel.vue
config/routes.rb

626 landing page redesign - comments

---

app/models/match.rb

In the P2P communication flow, we're not adding a status to the `Match` we're creating and this makes the `/matches` error out as [we're assuming that all matches will have a status](https://github.com/rubyforgood/mutual-aid/blob/main/app/views/matches/index.html.erb#L44). This change adds a `match_confirmed` status to the `Match` which takes care of that issue.

Confirms match in P2P flow

---

app/javascript/pages/browse/TileListItem.vue

Currently, the `view` and `respond` buttons on the contributions tile view aren't grouped together and the UI looks weird.
This change groups them together.

Groups view & respond buttons together on contributions page

---

README.md
doc/contributing.md

Brings `README.md` and `doc/contributing.md` up to date now that we're done with Ruby for Good fall 2020 and entering hacktoberfest.

Update readme and contribution guide post Ruby for Good weekend

---

CHANGELOG.md

Went through and collected all our recent changes into the Changelog.
Would love some editorial eyes :)

Changelog entries for v0.3

---

.github/pull_request_template.md

Noticed a typo in the PR template, nothing grande really.
Uses contributor instead of contributer.

Fixes a typo in the PR template

---

doc/contributing.md

Now that we've rearranged the GitHub project boards some, let's update the contribution guide to reflect the difference
I'm definitely interested in what developers newer to this project think about these changes and the board layout

Update contributing.md to reflect new project boards

---

README.md
app/controllers/public_pages_controller.rb
config/routes.rb
doc/contributing.md
spec/requests/public_pages_spec.rb

Resolves #672. 
So I basically added 2 badges for up(deployed) status of the apps.
I was using [this repo](https://github.com/pussinboots/heroku-badge) for the badges, I was also considering [this](https://github.com/chrisjh/heroku-shields), but the first one looks better to me, as it is more recent, has more options, and doesn't show 'up' on apps that do not exist 😆. 
Probably we need to find a solution for version deployed badge, maybe move to separate issue or close the issue if it's not possible.
I am not sure that we can show deployed version, at least I didn't find any solution for that (if we can please tell me how).

Add up/down badges for Heroku to README.md

---

app/views/admin/landing_page.html.erb

glossary path

---

app/assets/stylesheets/bulma_simple_form_customization.scss
package-lock.json

PR for #776 
Changed up focus outline for button to color that meets contrast guidelines with page's white background and button's light blue color.
-- **Would like to note, I don't have experience with Ruby + Bulma SCSS but looked through documentation and believe I've added CSS correctly to bulma_simple_form_customization. Please let me know if there are any errors!**
-- **Unsure if focus CSS change is needed for CHANGELOG but happy to add it if needed!**
WCAG 1.4.11 states UI elements should meet 3:1 ratio. Black/dark gray is used throughout the site which I chose to stick with color scheme. In adjusting the colors, the dark gray outline with the white background reaches 10.9:1 contrast ratio which is well past the requirement 
Next, meeting 1.4.11 again, I tested the turquoise/light …

Adjusted focus outline for buttons

---

app/assets/stylesheets/bulma_simple_form_customization.scss

focus outline rgba fix
